git add   Makefile.in
git add   aclocal.m4
git add   allinone/allinone.sln
git add   common/Makefile.in
git add   common/appendable.cpp
git add   common/bmpset.cpp
git add   common/common.vcxproj
git add   common/common.vcxproj.filters
git add   common/listformatter.cpp
git add   common/locmap.c
git add   common/messagepattern.cpp
git add   common/normalizer2.cpp
git add   common/putil.cpp
git add   common/putilimp.h
git add   common/stringtriebuilder.cpp
git add   common/ucnv.c
git add   common/ucnv2022.cpp
git add   common/ucnv_bld.cpp
git add   common/ucnv_ext.cpp
git add   common/ucnv_ext.h
git add   common/ucnvmbcs.c
git add   common/ucnvmbcs.h
git add   common/uiter.cpp
git add   common/uloc.cpp
git add   common/uloc_tag.c
git add   common/unicode/appendable.h
git add   common/unicode/brkiter.h
git add   common/unicode/dbbi.h
git add   common/unicode/enumset.h
git add   common/unicode/icudataver.h
git add   common/unicode/idna.h
git add   common/unicode/listformatter.h
git add   common/unicode/locid.h
git add   common/unicode/messagepattern.h
git add   common/unicode/normalizer2.h
git add   common/unicode/platform.h
git add   common/unicode/rbbi.h
git add   common/unicode/rep.h
git add   common/unicode/stringtriebuilder.h
git add   common/unicode/ubrk.h
git add   common/unicode/uchar.h
git add   common/unicode/uconfig.h
git add   common/unicode/uidna.h
git add   common/unicode/uloc.h
git add   common/unicode/unistr.h
git add   common/unicode/unorm2.h
git add   common/unicode/uobject.h
git add   common/unicode/urename.h
git add   common/unicode/uscript.h
git add   common/unicode/utf16.h
git add   common/unicode/utf8.h
git add   common/unicode/uvernum.h
git add   common/uniset.cpp
git add   common/unisetspan.cpp
git add   common/unistr.cpp
git add   common/uobject.cpp
git add   common/uresbund.cpp
git add   common/utext.cpp
git add   common/utf_impl.c
git add   common/uts46.cpp
git add   config/mh-cygwin-msvc
git add   config/mh-mingw
git add   configure
git add   data/Makefile.in
git add   data/brkitr/brkfiles.mk
git add   data/brkitr/char.txt
git add   data/brkitr/el.txt
git add   data/brkitr/en.txt
git add   data/brkitr/en_US.txt
git add   data/brkitr/en_US_POSIX.txt
git add   data/brkitr/fi.txt
git add   data/brkitr/ja.txt
git add   data/brkitr/root.txt
git add   data/brkitr/word.txt
git add   data/build.xml
git add   data/coll/af.txt
git add   data/coll/af_NA.txt
git add   data/coll/af_ZA.txt
git add   data/coll/ar.txt
git add   data/coll/ar_001.txt
git add   data/coll/ar_AE.txt
git add   data/coll/ar_BH.txt
git add   data/coll/ar_DJ.txt
git add   data/coll/ar_DZ.txt
git add   data/coll/ar_EG.txt
git add   data/coll/ar_EH.txt
git add   data/coll/ar_ER.txt
git add   data/coll/ar_IL.txt
git add   data/coll/ar_IQ.txt
git add   data/coll/ar_JO.txt
git add   data/coll/ar_KM.txt
git add   data/coll/ar_KW.txt
git add   data/coll/ar_LB.txt
git add   data/coll/ar_LY.txt
git add   data/coll/ar_MA.txt
git add   data/coll/ar_MR.txt
git add   data/coll/ar_OM.txt
git add   data/coll/ar_PS.txt
git add   data/coll/ar_QA.txt
git add   data/coll/ar_SA.txt
git add   data/coll/ar_SD.txt
git add   data/coll/ar_SO.txt
git add   data/coll/ar_SY.txt
git add   data/coll/ar_TD.txt
git add   data/coll/ar_TN.txt
git add   data/coll/ar_YE.txt
git add   data/coll/as.txt
git add   data/coll/as_IN.txt
git add   data/coll/az.txt
git add   data/coll/az_Latn.txt
git add   data/coll/az_Latn_AZ.txt
git add   data/coll/be.txt
git add   data/coll/be_BY.txt
git add   data/coll/bg.txt
git add   data/coll/bg_BG.txt
git add   data/coll/bn.txt
git add   data/coll/bn_BD.txt
git add   data/coll/bn_IN.txt
git add   data/coll/bs.txt
git add   data/coll/bs_Cyrl.txt
git add   data/coll/bs_Cyrl_BA.txt
git add   data/coll/bs_Latn.txt
git add   data/coll/bs_Latn_BA.txt
git add   data/coll/ca.txt
git add   data/coll/ca_AD.txt
git add   data/coll/ca_ES.txt
git add   data/coll/chr.txt
git add   data/coll/chr_US.txt
git add   data/coll/colfiles.mk
git add   data/coll/cs.txt
git add   data/coll/cs_CZ.txt
git add   data/coll/cy.txt
git add   data/coll/cy_GB.txt
git add   data/coll/da.txt
git add   data/coll/da_DK.txt
git add   data/coll/de.txt
git add   data/coll/de_.txt
git add   data/coll/de_AT.txt
git add   data/coll/de_BE.txt
git add   data/coll/de_CH.txt
git add   data/coll/de_DE.txt
git add   data/coll/de_LI.txt
git add   data/coll/de_LU.txt
git add   data/coll/de__PHONEBOOK.txt
git add   data/coll/dz.txt
git add   data/coll/ee.txt
git add   data/coll/ee_GH.txt
git add   data/coll/ee_TG.txt
git add   data/coll/el.txt
git add   data/coll/el_CY.txt
git add   data/coll/el_GR.txt
git add   data/coll/en.txt
git add   data/coll/en_150.txt
git add   data/coll/en_AG.txt
git add   data/coll/en_AS.txt
git add   data/coll/en_AU.txt
git add   data/coll/en_BB.txt
git add   data/coll/en_BE.txt
git add   data/coll/en_BM.txt
git add   data/coll/en_BS.txt
git add   data/coll/en_BW.txt
git add   data/coll/en_BZ.txt
git add   data/coll/en_CA.txt
git add   data/coll/en_CM.txt
git add   data/coll/en_DM.txt
git add   data/coll/en_FJ.txt
git add   data/coll/en_FM.txt
git add   data/coll/en_GB.txt
git add   data/coll/en_GD.txt
git add   data/coll/en_GG.txt
git add   data/coll/en_GH.txt
git add   data/coll/en_GI.txt
git add   data/coll/en_GM.txt
git add   data/coll/en_GU.txt
git add   data/coll/en_HK.txt
git add   data/coll/en_IE.txt
git add   data/coll/en_IM.txt
git add   data/coll/en_IN.txt
git add   data/coll/en_JE.txt
git add   data/coll/en_JM.txt
git add   data/coll/en_KE.txt
git add   data/coll/en_KI.txt
git add   data/coll/en_KN.txt
git add   data/coll/en_KY.txt
git add   data/coll/en_LC.txt
git add   data/coll/en_LR.txt
git add   data/coll/en_LS.txt
git add   data/coll/en_MG.txt
git add   data/coll/en_MH.txt
git add   data/coll/en_MP.txt
git add   data/coll/en_MT.txt
git add   data/coll/en_MU.txt
git add   data/coll/en_MW.txt
git add   data/coll/en_NA.txt
git add   data/coll/en_NG.txt
git add   data/coll/en_NZ.txt
git add   data/coll/en_PG.txt
git add   data/coll/en_PH.txt
git add   data/coll/en_PK.txt
git add   data/coll/en_PR.txt
git add   data/coll/en_PW.txt
git add   data/coll/en_SB.txt
git add   data/coll/en_SC.txt
git add   data/coll/en_SG.txt
git add   data/coll/en_SL.txt
git add   data/coll/en_SS.txt
git add   data/coll/en_TC.txt
git add   data/coll/en_TO.txt
git add   data/coll/en_TT.txt
git add   data/coll/en_TZ.txt
git add   data/coll/en_UG.txt
git add   data/coll/en_UM.txt
git add   data/coll/en_US.txt
git add   data/coll/en_US_POSIX.txt
git add   data/coll/en_VC.txt
git add   data/coll/en_VG.txt
git add   data/coll/en_VI.txt
git add   data/coll/en_VU.txt
git add   data/coll/en_WS.txt
git add   data/coll/en_ZA.txt
git add   data/coll/en_ZM.txt
git add   data/coll/en_ZW.txt
git add   data/coll/eo.txt
git add   data/coll/es.txt
git add   data/coll/es_.txt
git add   data/coll/es_419.txt
git add   data/coll/es_AR.txt
git add   data/coll/es_BO.txt
git add   data/coll/es_CL.txt
git add   data/coll/es_CO.txt
git add   data/coll/es_CR.txt
git add   data/coll/es_CU.txt
git add   data/coll/es_DO.txt
git add   data/coll/es_EA.txt
git add   data/coll/es_EC.txt
git add   data/coll/es_ES.txt
git add   data/coll/es_GQ.txt
git add   data/coll/es_GT.txt
git add   data/coll/es_HN.txt
git add   data/coll/es_IC.txt
git add   data/coll/es_MX.txt
git add   data/coll/es_NI.txt
git add   data/coll/es_PA.txt
git add   data/coll/es_PE.txt
git add   data/coll/es_PH.txt
git add   data/coll/es_PR.txt
git add   data/coll/es_PY.txt
git add   data/coll/es_SV.txt
git add   data/coll/es_US.txt
git add   data/coll/es_UY.txt
git add   data/coll/es_VE.txt
git add   data/coll/es__TRADITIONAL.txt
git add   data/coll/et.txt
git add   data/coll/et_EE.txt
git add   data/coll/fa.txt
git add   data/coll/fa_AF.txt
git add   data/coll/fa_IR.txt
git add   data/coll/fi.txt
git add   data/coll/fi_FI.txt
git add   data/coll/fil.txt
git add   data/coll/fil_PH.txt
git add   data/coll/fo.txt
git add   data/coll/fo_FO.txt
git add   data/coll/fr.txt
git add   data/coll/fr_BE.txt
git add   data/coll/fr_BF.txt
git add   data/coll/fr_BI.txt
git add   data/coll/fr_BJ.txt
git add   data/coll/fr_BL.txt
git add   data/coll/fr_CA.txt
git add   data/coll/fr_CD.txt
git add   data/coll/fr_CF.txt
git add   data/coll/fr_CG.txt
git add   data/coll/fr_CH.txt
git add   data/coll/fr_CI.txt
git add   data/coll/fr_CM.txt
git add   data/coll/fr_DJ.txt
git add   data/coll/fr_DZ.txt
git add   data/coll/fr_FR.txt
git add   data/coll/fr_GA.txt
git add   data/coll/fr_GN.txt
git add   data/coll/fr_GP.txt
git add   data/coll/fr_GQ.txt
git add   data/coll/fr_HT.txt
git add   data/coll/fr_KM.txt
git add   data/coll/fr_LU.txt
git add   data/coll/fr_MA.txt
git add   data/coll/fr_MC.txt
git add   data/coll/fr_MF.txt
git add   data/coll/fr_MG.txt
git add   data/coll/fr_ML.txt
git add   data/coll/fr_MQ.txt
git add   data/coll/fr_MR.txt
git add   data/coll/fr_MU.txt
git add   data/coll/fr_NC.txt
git add   data/coll/fr_NE.txt
git add   data/coll/fr_PF.txt
git add   data/coll/fr_RE.txt
git add   data/coll/fr_RW.txt
git add   data/coll/fr_SC.txt
git add   data/coll/fr_SN.txt
git add   data/coll/fr_SY.txt
git add   data/coll/fr_TD.txt
git add   data/coll/fr_TG.txt
git add   data/coll/fr_TN.txt
git add   data/coll/fr_VU.txt
git add   data/coll/ga.txt
git add   data/coll/ga_IE.txt
git add   data/coll/gu.txt
git add   data/coll/gu_IN.txt
git add   data/coll/ha.txt
git add   data/coll/ha_Latn.txt
git add   data/coll/ha_Latn_GH.txt
git add   data/coll/ha_Latn_NE.txt
git add   data/coll/ha_Latn_NG.txt
git add   data/coll/haw.txt
git add   data/coll/he.txt
git add   data/coll/he_IL.txt
git add   data/coll/hi.txt
git rm data/coll/hi_.txt
git add   data/coll/hi_IN.txt
git rm data/coll/hi__DIRECT.txt
git add   data/coll/hr.txt
git add   data/coll/hr_BA.txt
git add   data/coll/hr_HR.txt
git add   data/coll/hu.txt
git add   data/coll/hu_HU.txt
git add   data/coll/hy.txt
git add   data/coll/hy_AM.txt
git add   data/coll/id.txt
git add   data/coll/id_ID.txt
git add   data/coll/ig.txt
git add   data/coll/ig_NG.txt
git add   data/coll/in.txt
git add   data/coll/in_ID.txt
git add   data/coll/is.txt
git add   data/coll/is_IS.txt
git add   data/coll/it.txt
git add   data/coll/it_CH.txt
git add   data/coll/it_IT.txt
git add   data/coll/it_SM.txt
git add   data/coll/iw.txt
git add   data/coll/iw_IL.txt
git add   data/coll/ja.txt
git add   data/coll/ja_JP.txt
git add   data/coll/ka.txt
git add   data/coll/ka_GE.txt
git add   data/coll/kk.txt
git add   data/coll/kk_KZ.txt
git add   data/coll/kl.txt
git add   data/coll/kl_GL.txt
git add   data/coll/km.txt
git add   data/coll/km_KH.txt
git add   data/coll/kn.txt
git add   data/coll/kn_IN.txt
git add   data/coll/ko.txt
git add   data/coll/ko_KP.txt
git add   data/coll/ko_KR.txt
git add   data/coll/kok.txt
git add   data/coll/kok_IN.txt
git add   data/coll/ln.txt
git add   data/coll/ln_AO.txt
git add   data/coll/ln_CD.txt
git add   data/coll/ln_CF.txt
git add   data/coll/ln_CG.txt
git add   data/coll/lt.txt
git add   data/coll/lt_LT.txt
git add   data/coll/lv.txt
git add   data/coll/lv_LV.txt
git add   data/coll/mk.txt
git add   data/coll/mk_MK.txt
git add   data/coll/ml.txt
git add   data/coll/ml_IN.txt
git add   data/coll/mo.txt
git add   data/coll/mr.txt
git add   data/coll/mr_IN.txt
git add   data/coll/ms.txt
git rm data/coll/ms_BN.txt
git rm data/coll/ms_MY.txt
git rm data/coll/ms_SG.txt
git add   data/coll/mt.txt
git add   data/coll/mt_MT.txt
git add   data/coll/my.txt
git add   data/coll/my_MM.txt
git add   data/coll/nb.txt
git add   data/coll/nb_NO.txt
git add   data/coll/nl.txt
git add   data/coll/nl_AW.txt
git add   data/coll/nl_BE.txt
git add   data/coll/nl_CW.txt
git add   data/coll/nl_NL.txt
git add   data/coll/nl_SR.txt
git add   data/coll/nl_SX.txt
git add   data/coll/nn.txt
git add   data/coll/nn_NO.txt
git add   data/coll/no.txt
git add   data/coll/no_NO.txt
git add   data/coll/om.txt
git add   data/coll/om_ET.txt
git add   data/coll/om_KE.txt
git add   data/coll/or.txt
git add   data/coll/or_IN.txt
git add   data/coll/pa.txt
git add   data/coll/pa_Arab.txt
git add   data/coll/pa_Arab_PK.txt
git add   data/coll/pa_Guru.txt
git add   data/coll/pa_Guru_IN.txt
git add   data/coll/pa_IN.txt
git add   data/coll/pl.txt
git add   data/coll/pl_PL.txt
git add   data/coll/ps.txt
git add   data/coll/ps_AF.txt
git add   data/coll/pt.txt
git add   data/coll/pt_AO.txt
git add   data/coll/pt_BR.txt
git add   data/coll/pt_CV.txt
git add   data/coll/pt_GW.txt
git add   data/coll/pt_MO.txt
git add   data/coll/pt_MZ.txt
git add   data/coll/pt_PT.txt
git add   data/coll/pt_ST.txt
git add   data/coll/pt_TL.txt
git add   data/coll/ro.txt
git add   data/coll/ro_MD.txt
git add   data/coll/ro_RO.txt
git add   data/coll/root.txt
git add   data/coll/ru.txt
git add   data/coll/ru_BY.txt
git add   data/coll/ru_KG.txt
git add   data/coll/ru_KZ.txt
git add   data/coll/ru_MD.txt
git add   data/coll/ru_RU.txt
git add   data/coll/ru_UA.txt
git add   data/coll/sh.txt
git add   data/coll/sh_BA.txt
git add   data/coll/sh_YU.txt
git add   data/coll/si.txt
git add   data/coll/si_LK.txt
git add   data/coll/sk.txt
git add   data/coll/sk_SK.txt
git add   data/coll/sl.txt
git add   data/coll/sl_SI.txt
git add   data/coll/sq.txt
git add   data/coll/sq_AL.txt
git add   data/coll/sq_MK.txt
git add   data/coll/sr.txt
git add   data/coll/sr_BA.txt
git add   data/coll/sr_Cyrl.txt
git add   data/coll/sr_Cyrl_BA.txt
git add   data/coll/sr_Cyrl_ME.txt
git add   data/coll/sr_Cyrl_RS.txt
git add   data/coll/sr_Latn.txt
git add   data/coll/sr_Latn_BA.txt
git add   data/coll/sr_Latn_ME.txt
git add   data/coll/sr_Latn_RS.txt
git add   data/coll/sr_ME.txt
git add   data/coll/sr_RS.txt
git add   data/coll/sv.txt
git add   data/coll/sv_AX.txt
git add   data/coll/sv_FI.txt
git add   data/coll/sv_SE.txt
git add   data/coll/sw.txt
git add   data/coll/sw_KE.txt
git add   data/coll/sw_TZ.txt
git add   data/coll/sw_UG.txt
git add   data/coll/ta.txt
git add   data/coll/ta_IN.txt
git add   data/coll/ta_LK.txt
git add   data/coll/ta_MY.txt
git add   data/coll/ta_SG.txt
git add   data/coll/te.txt
git add   data/coll/te_IN.txt
git add   data/coll/th.txt
git add   data/coll/th_TH.txt
git add   data/coll/to.txt
git add   data/coll/to_TO.txt
git add   data/coll/tr.txt
git add   data/coll/tr_CY.txt
git add   data/coll/tr_TR.txt
git add   data/coll/uk.txt
git add   data/coll/uk_UA.txt
git add   data/coll/ur.txt
git add   data/coll/ur_IN.txt
git add   data/coll/ur_PK.txt
git add   data/coll/vi.txt
git add   data/coll/vi_VN.txt
git add   data/coll/yo.txt
git add   data/coll/yo_NG.txt
git add   data/coll/zh.txt
git rm data/coll/zh_.txt
git add   data/coll/zh_CN.txt
git add   data/coll/zh_HK.txt
git add   data/coll/zh_Hans.txt
git add   data/coll/zh_Hans_CN.txt
git add   data/coll/zh_Hans_SG.txt
git add   data/coll/zh_Hant.txt
git add   data/coll/zh_Hant_HK.txt
git add   data/coll/zh_Hant_MO.txt
git add   data/coll/zh_Hant_TW.txt
git add   data/coll/zh_MO.txt
git add   data/coll/zh_SG.txt
git add   data/coll/zh_TW.txt
git rm data/coll/zh_TW_STROKE.txt
git rm data/coll/zh__PINYIN.txt
git add   data/coll/zu.txt
git add   data/coll/zu_ZA.txt
git add   data/curr/af.txt
git add   data/curr/af_NA.txt
git add   data/curr/agq.txt
git add   data/curr/ak.txt
git add   data/curr/am.txt
git add   data/curr/ar.txt
git add   data/curr/as.txt
git add   data/curr/asa.txt
git add   data/curr/az.txt
git add   data/curr/az_AZ.txt
git add   data/curr/az_Cyrl.txt
git add   data/curr/az_Latn.txt
git add   data/curr/az_Latn_AZ.txt
git add   data/curr/bas.txt
git add   data/curr/be.txt
git add   data/curr/bem.txt
git add   data/curr/bez.txt
git add   data/curr/bg.txt
git add   data/curr/bm.txt
git add   data/curr/bn.txt
git add   data/curr/bn_IN.txt
git add   data/curr/bo.txt
git add   data/curr/br.txt
git add   data/curr/brx.txt
git add   data/curr/bs.txt
git add   data/curr/bs_BA.txt
git add   data/curr/bs_Cyrl.txt
git add   data/curr/bs_Latn.txt
git add   data/curr/bs_Latn_BA.txt
git add   data/curr/ca.txt
git add   data/curr/cgg.txt
git add   data/curr/chr.txt
git add   data/curr/cs.txt
git add   data/curr/cy.txt
git add   data/curr/da.txt
git add   data/curr/dav.txt
git add   data/curr/de.txt
git add   data/curr/de_LU.txt
git add   data/curr/dje.txt
git add   data/curr/dua.txt
git add   data/curr/dyo.txt
git add   data/curr/dz.txt
git add   data/curr/ebu.txt
git add   data/curr/ee.txt
git add   data/curr/el.txt
git add   data/curr/en.txt
git add   data/curr/en_AU.txt
git add   data/curr/en_BB.txt
git add   data/curr/en_BM.txt
git add   data/curr/en_BW.txt
git add   data/curr/en_BZ.txt
git add   data/curr/en_CA.txt
git add   data/curr/en_GB.txt
git add   data/curr/en_HK.txt
git add   data/curr/en_JM.txt
git add   data/curr/en_MT.txt
git add   data/curr/en_NA.txt
git add   data/curr/en_NH.txt
git add   data/curr/en_NZ.txt
git add   data/curr/en_PH.txt
git add   data/curr/en_PK.txt
git add   data/curr/en_RH.txt
git add   data/curr/en_SG.txt
git add   data/curr/en_TT.txt
git add   data/curr/en_VU.txt
git add   data/curr/en_ZA.txt
git add   data/curr/en_ZW.txt
git add   data/curr/eo.txt
git add   data/curr/es.txt
git add   data/curr/es_AR.txt
git add   data/curr/es_BO.txt
git add   data/curr/es_CL.txt
git add   data/curr/es_CO.txt
git add   data/curr/es_CR.txt
git add   data/curr/es_DO.txt
git add   data/curr/es_EC.txt
git add   data/curr/es_GT.txt
git add   data/curr/es_HN.txt
git add   data/curr/es_MX.txt
git add   data/curr/es_NI.txt
git add   data/curr/es_PA.txt
git add   data/curr/es_PE.txt
git add   data/curr/es_PR.txt
git add   data/curr/es_PY.txt
git add   data/curr/es_US.txt
git add   data/curr/es_UY.txt
git add   data/curr/es_VE.txt
git add   data/curr/et.txt
git add   data/curr/eu.txt
git add   data/curr/ewo.txt
git add   data/curr/fa.txt
git add   data/curr/fa_AF.txt
git add   data/curr/ff.txt
git add   data/curr/fi.txt
git add   data/curr/fil.txt
git add   data/curr/fil_PH.txt
git add   data/curr/fo.txt
git add   data/curr/fr.txt
git add   data/curr/fr_BI.txt
git add   data/curr/fr_CA.txt
git add   data/curr/fr_DJ.txt
git add   data/curr/fr_GN.txt
git add   data/curr/fr_KM.txt
git add   data/curr/fr_LU.txt
git add   data/curr/ga.txt
git add   data/curr/gl.txt
git add   data/curr/gsw.txt
git add   data/curr/gu.txt
git add   data/curr/guz.txt
git add   data/curr/gv.txt
git add   data/curr/ha.txt
git add   data/curr/ha_GH.txt
git add   data/curr/ha_Latn.txt
git add   data/curr/ha_Latn_GH.txt
git add   data/curr/ha_Latn_NE.txt
git add   data/curr/ha_Latn_NG.txt
git add   data/curr/ha_NE.txt
git add   data/curr/ha_NG.txt
git add   data/curr/haw.txt
git add   data/curr/he.txt
git add   data/curr/he_IL.txt
git add   data/curr/hi.txt
git add   data/curr/hr.txt
git add   data/curr/hu.txt
git add   data/curr/hy.txt
git add   data/curr/id.txt
git add   data/curr/id_ID.txt
git add   data/curr/ig.txt
git add   data/curr/ii.txt
git add   data/curr/in.txt
git add   data/curr/in_ID.txt
git add   data/curr/is.txt
git add   data/curr/it.txt
git add   data/curr/iw.txt
git add   data/curr/iw_IL.txt
git add   data/curr/ja.txt
git add   data/curr/ja_JP.txt
git add   data/curr/ja_JP_TRADITIONAL.txt
git add   data/curr/jgo.txt
git add   data/curr/jmc.txt
git add   data/curr/ka.txt
git add   data/curr/kab.txt
git add   data/curr/kam.txt
git add   data/curr/kde.txt
git add   data/curr/kea.txt
git add   data/curr/khq.txt
git add   data/curr/ki.txt
git add   data/curr/kk.txt
git add   data/curr/kk_Cyrl.txt
git add   data/curr/kk_Cyrl_KZ.txt
git add   data/curr/kk_KZ.txt
git add   data/curr/kl.txt
git add   data/curr/kln.txt
git add   data/curr/km.txt
git add   data/curr/kn.txt
git add   data/curr/ko.txt
git add   data/curr/kok.txt
git add   data/curr/ks.txt
git add   data/curr/ks_Arab.txt
git add   data/curr/ks_Arab_IN.txt
git add   data/curr/ks_IN.txt
git add   data/curr/ksb.txt
git add   data/curr/ksf.txt
git add   data/curr/kw.txt
git add   data/curr/lag.txt
git add   data/curr/lg.txt
git add   data/curr/ln.txt
git add   data/curr/lo.txt
git add   data/curr/lt.txt
git add   data/curr/lu.txt
git add   data/curr/luo.txt
git add   data/curr/luy.txt
git add   data/curr/lv.txt
git add   data/curr/mas.txt
git add   data/curr/mas_TZ.txt
git add   data/curr/mer.txt
git add   data/curr/mfe.txt
git add   data/curr/mg.txt
git add   data/curr/mgh.txt
git add   data/curr/mgo.txt
git add   data/curr/mk.txt
git add   data/curr/ml.txt
git add   data/curr/mo.txt
git add   data/curr/mr.txt
git add   data/curr/ms.txt
git add   data/curr/ms_BN.txt
git add   data/curr/mt.txt
git add   data/curr/mua.txt
git add   data/curr/my.txt
git add   data/curr/naq.txt
git add   data/curr/nb.txt
git add   data/curr/nb_NO.txt
git add   data/curr/nd.txt
git add   data/curr/ne.txt
git add   data/curr/ne_IN.txt
git add   data/curr/nl.txt
git add   data/curr/nl_AW.txt
git add   data/curr/nl_CW.txt
git add   data/curr/nl_SX.txt
git add   data/curr/nmg.txt
git add   data/curr/nn.txt
git add   data/curr/nn_NO.txt
git add   data/curr/no.txt
git add   data/curr/no_NO.txt
git add   data/curr/no_NO_NY.txt
git add   data/curr/nus.txt
git add   data/curr/nyn.txt
git add   data/curr/om.txt
git add   data/curr/om_KE.txt
git add   data/curr/or.txt
git add   data/curr/pa.txt
git add   data/curr/pa_Arab.txt
git add   data/curr/pa_Arab_PK.txt
git add   data/curr/pa_Guru.txt
git add   data/curr/pa_Guru_IN.txt
git add   data/curr/pa_IN.txt
git add   data/curr/pa_PK.txt
git add   data/curr/pl.txt
git add   data/curr/pool.res
git add   data/curr/ps.txt
git add   data/curr/pt.txt
git add   data/curr/pt_AO.txt
git add   data/curr/pt_MZ.txt
git add   data/curr/pt_PT.txt
git add   data/curr/pt_ST.txt
git add   data/curr/resfiles.mk
git add   data/curr/rm.txt
git add   data/curr/rn.txt
git add   data/curr/ro.txt
git add   data/curr/ro_MD.txt
git add   data/curr/rof.txt
git add   data/curr/root.txt
git add   data/curr/ru.txt
git add   data/curr/rw.txt
git add   data/curr/rwk.txt
git add   data/curr/saq.txt
git add   data/curr/sbp.txt
git add   data/curr/seh.txt
git add   data/curr/ses.txt
git add   data/curr/sg.txt
git add   data/curr/sh.txt
git add   data/curr/sh_BA.txt
git add   data/curr/sh_CS.txt
git add   data/curr/sh_YU.txt
git add   data/curr/shi.txt
git add   data/curr/shi_Latn.txt
git rm data/curr/shi_Latn_MA.txt
git add   data/curr/shi_MA.txt
git add   data/curr/shi_Tfng.txt
git add   data/curr/si.txt
git add   data/curr/sk.txt
git add   data/curr/sl.txt
git add   data/curr/sn.txt
git add   data/curr/so.txt
git add   data/curr/so_DJ.txt
git add   data/curr/so_ET.txt
git add   data/curr/so_KE.txt
git add   data/curr/sq.txt
git add   data/curr/sr.txt
git add   data/curr/sr_BA.txt
git add   data/curr/sr_CS.txt
git add   data/curr/sr_Cyrl.txt
git add   data/curr/sr_Cyrl_BA.txt
git add   data/curr/sr_Cyrl_CS.txt
git add   data/curr/sr_Cyrl_RS.txt
git add   data/curr/sr_Cyrl_YU.txt
git add   data/curr/sr_Latn.txt
git add   data/curr/sr_Latn_BA.txt
git add   data/curr/sr_Latn_CS.txt
git add   data/curr/sr_Latn_ME.txt
git add   data/curr/sr_Latn_RS.txt
git add   data/curr/sr_Latn_YU.txt
git add   data/curr/sr_ME.txt
git add   data/curr/sr_RS.txt
git add   data/curr/sr_YU.txt
git add   data/curr/supplementalData.txt
git add   data/curr/sv.txt
git add   data/curr/sw.txt
git add   data/curr/swc.txt
git add   data/curr/ta.txt
git add   data/curr/ta_LK.txt
git add   data/curr/ta_MY.txt
git add   data/curr/ta_SG.txt
git add   data/curr/te.txt
git add   data/curr/teo.txt
git add   data/curr/teo_KE.txt
git add   data/curr/th.txt
git add   data/curr/th_TH.txt
git add   data/curr/th_TH_TRADITIONAL.txt
git add   data/curr/ti.txt
git add   data/curr/ti_ER.txt
git add   data/curr/tl.txt
git add   data/curr/tl_PH.txt
git add   data/curr/to.txt
git add   data/curr/tr.txt
git add   data/curr/twq.txt
git add   data/curr/tzm.txt
git add   data/curr/tzm_Latn.txt
git add   data/curr/tzm_Latn_MA.txt
git add   data/curr/tzm_MA.txt
git add   data/curr/uk.txt
git add   data/curr/ur.txt
git add   data/curr/uz.txt
git add   data/curr/uz_AF.txt
git add   data/curr/uz_Arab.txt
git add   data/curr/uz_Arab_AF.txt
git add   data/curr/uz_Cyrl.txt
git add   data/curr/uz_Cyrl_UZ.txt
git add   data/curr/uz_Latn.txt
git add   data/curr/uz_UZ.txt
git add   data/curr/vai.txt
git add   data/curr/vai_LR.txt
git add   data/curr/vai_Latn.txt
git add   data/curr/vai_Vaii.txt
git add   data/curr/vai_Vaii_LR.txt
git add   data/curr/vi.txt
git add   data/curr/vun.txt
git add   data/curr/xog.txt
git add   data/curr/yav.txt
git add   data/curr/yo.txt
git add   data/curr/zh.txt
git add   data/curr/zh_CN.txt
git add   data/curr/zh_HK.txt
git add   data/curr/zh_Hans.txt
git add   data/curr/zh_Hans_CN.txt
git add   data/curr/zh_Hans_HK.txt
git add   data/curr/zh_Hans_MO.txt
git add   data/curr/zh_Hans_SG.txt
git add   data/curr/zh_Hant.txt
git add   data/curr/zh_Hant_HK.txt
git add   data/curr/zh_Hant_MO.txt
git add   data/curr/zh_Hant_TW.txt
git add   data/curr/zh_MO.txt
git add   data/curr/zh_SG.txt
git add   data/curr/zh_TW.txt
git add   data/curr/zu.txt
git add   data/icu-config.xml
git add   data/icu-locale-deprecates.xml
git add   data/lang/af.txt
git add   data/lang/agq.txt
git add   data/lang/ak.txt
git add   data/lang/am.txt
git add   data/lang/ar.txt
git add   data/lang/as.txt
git add   data/lang/asa.txt
git add   data/lang/az.txt
git add   data/lang/az_AZ.txt
git add   data/lang/az_Cyrl.txt
git add   data/lang/az_Latn.txt
git add   data/lang/az_Latn_AZ.txt
git add   data/lang/bas.txt
git add   data/lang/be.txt
git add   data/lang/bem.txt
git add   data/lang/bez.txt
git add   data/lang/bg.txt
git add   data/lang/bm.txt
git add   data/lang/bn.txt
git add   data/lang/bn_IN.txt
git add   data/lang/bo.txt
git add   data/lang/br.txt
git add   data/lang/brx.txt
git add   data/lang/bs.txt
git add   data/lang/bs_BA.txt
git add   data/lang/bs_Cyrl.txt
git add   data/lang/bs_Latn.txt
git add   data/lang/bs_Latn_BA.txt
git add   data/lang/ca.txt
git add   data/lang/cgg.txt
git add   data/lang/chr.txt
git add   data/lang/cs.txt
git add   data/lang/cy.txt
git add   data/lang/da.txt
git add   data/lang/dav.txt
git add   data/lang/de.txt
git add   data/lang/de_CH.txt
git add   data/lang/dje.txt
git add   data/lang/dua.txt
git add   data/lang/dyo.txt
git add   data/lang/dz.txt
git add   data/lang/ebu.txt
git add   data/lang/ee.txt
git add   data/lang/el.txt
git add   data/lang/en.txt
git add   data/lang/en_GB.txt
git add   data/lang/en_NH.txt
git add   data/lang/en_RH.txt
git add   data/lang/en_VU.txt
git add   data/lang/en_ZW.txt
git add   data/lang/eo.txt
git add   data/lang/es.txt
git add   data/lang/es_419.txt
git add   data/lang/es_CL.txt
git add   data/lang/et.txt
git add   data/lang/eu.txt
git add   data/lang/ewo.txt
git add   data/lang/fa.txt
git add   data/lang/fa_AF.txt
git add   data/lang/ff.txt
git add   data/lang/fi.txt
git add   data/lang/fil.txt
git add   data/lang/fil_PH.txt
git add   data/lang/fo.txt
git add   data/lang/fr.txt
git add   data/lang/fr_CA.txt
git add   data/lang/ga.txt
git add   data/lang/gl.txt
git add   data/lang/gsw.txt
git add   data/lang/gu.txt
git add   data/lang/guz.txt
git add   data/lang/gv.txt
git add   data/lang/ha.txt
git add   data/lang/ha_GH.txt
git add   data/lang/ha_Latn.txt
git add   data/lang/ha_Latn_GH.txt
git add   data/lang/ha_Latn_NE.txt
git add   data/lang/ha_Latn_NG.txt
git add   data/lang/ha_NE.txt
git add   data/lang/ha_NG.txt
git add   data/lang/haw.txt
git add   data/lang/he.txt
git add   data/lang/he_IL.txt
git add   data/lang/hi.txt
git add   data/lang/hr.txt
git add   data/lang/hu.txt
git add   data/lang/hy.txt
git add   data/lang/id.txt
git add   data/lang/id_ID.txt
git add   data/lang/ig.txt
git add   data/lang/ii.txt
git add   data/lang/in.txt
git add   data/lang/in_ID.txt
git add   data/lang/is.txt
git add   data/lang/it.txt
git add   data/lang/iw.txt
git add   data/lang/iw_IL.txt
git add   data/lang/ja.txt
git add   data/lang/ja_JP.txt
git add   data/lang/ja_JP_TRADITIONAL.txt
git add   data/lang/jgo.txt
git add   data/lang/jmc.txt
git add   data/lang/ka.txt
git add   data/lang/kab.txt
git add   data/lang/kam.txt
git add   data/lang/kde.txt
git add   data/lang/kea.txt
git add   data/lang/khq.txt
git add   data/lang/ki.txt
git add   data/lang/kk.txt
git add   data/lang/kk_Cyrl.txt
git add   data/lang/kk_Cyrl_KZ.txt
git add   data/lang/kk_KZ.txt
git add   data/lang/kl.txt
git add   data/lang/kln.txt
git add   data/lang/km.txt
git add   data/lang/kn.txt
git add   data/lang/ko.txt
git add   data/lang/kok.txt
git add   data/lang/ks.txt
git add   data/lang/ks_Arab.txt
git add   data/lang/ks_Arab_IN.txt
git add   data/lang/ks_IN.txt
git add   data/lang/ksb.txt
git add   data/lang/ksf.txt
git add   data/lang/kw.txt
git add   data/lang/lag.txt
git add   data/lang/lg.txt
git add   data/lang/ln.txt
git add   data/lang/lo.txt
git add   data/lang/lt.txt
git add   data/lang/lu.txt
git add   data/lang/luo.txt
git add   data/lang/luy.txt
git add   data/lang/lv.txt
git add   data/lang/mas.txt
git add   data/lang/mer.txt
git add   data/lang/mfe.txt
git add   data/lang/mg.txt
git add   data/lang/mgh.txt
git add   data/lang/mgo.txt
git add   data/lang/mk.txt
git add   data/lang/ml.txt
git add   data/lang/mo.txt
git add   data/lang/mr.txt
git add   data/lang/ms.txt
git add   data/lang/mt.txt
git add   data/lang/mua.txt
git add   data/lang/my.txt
git add   data/lang/naq.txt
git add   data/lang/nb.txt
git add   data/lang/nb_NO.txt
git add   data/lang/nd.txt
git add   data/lang/ne.txt
git add   data/lang/nl.txt
git add   data/lang/nl_BE.txt
git add   data/lang/nmg.txt
git add   data/lang/nn.txt
git add   data/lang/nn_NO.txt
git add   data/lang/no.txt
git add   data/lang/no_NO.txt
git add   data/lang/no_NO_NY.txt
git add   data/lang/nus.txt
git add   data/lang/nyn.txt
git add   data/lang/om.txt
git add   data/lang/or.txt
git add   data/lang/pa.txt
git add   data/lang/pa_Arab.txt
git add   data/lang/pa_Arab_PK.txt
git add   data/lang/pa_Guru.txt
git add   data/lang/pa_Guru_IN.txt
git add   data/lang/pa_IN.txt
git add   data/lang/pa_PK.txt
git add   data/lang/pl.txt
git add   data/lang/pool.res
git add   data/lang/ps.txt
git add   data/lang/pt.txt
git add   data/lang/pt_PT.txt
git add   data/lang/resfiles.mk
git add   data/lang/rm.txt
git add   data/lang/rn.txt
git add   data/lang/ro.txt
git add   data/lang/ro_MD.txt
git add   data/lang/rof.txt
git add   data/lang/root.txt
git add   data/lang/ru.txt
git add   data/lang/ru_UA.txt
git add   data/lang/rw.txt
git add   data/lang/rwk.txt
git add   data/lang/saq.txt
git add   data/lang/sbp.txt
git add   data/lang/seh.txt
git add   data/lang/ses.txt
git add   data/lang/sg.txt
git add   data/lang/sh.txt
git add   data/lang/sh_BA.txt
git add   data/lang/sh_CS.txt
git add   data/lang/sh_YU.txt
git add   data/lang/shi.txt
git add   data/lang/shi_Latn.txt
git rm data/lang/shi_Latn_MA.txt
git add   data/lang/shi_MA.txt
git add   data/lang/shi_Tfng.txt
git add   data/lang/si.txt
git add   data/lang/sk.txt
git add   data/lang/sl.txt
git add   data/lang/sn.txt
git add   data/lang/so.txt
git add   data/lang/sq.txt
git add   data/lang/sr.txt
git add   data/lang/sr_BA.txt
git add   data/lang/sr_CS.txt
git add   data/lang/sr_Cyrl.txt
git add   data/lang/sr_Cyrl_BA.txt
git add   data/lang/sr_Cyrl_CS.txt
git add   data/lang/sr_Cyrl_RS.txt
git add   data/lang/sr_Cyrl_YU.txt
git add   data/lang/sr_Latn.txt
git add   data/lang/sr_Latn_BA.txt
git add   data/lang/sr_Latn_CS.txt
git add   data/lang/sr_Latn_ME.txt
git add   data/lang/sr_Latn_RS.txt
git add   data/lang/sr_Latn_YU.txt
git add   data/lang/sr_ME.txt
git add   data/lang/sr_RS.txt
git add   data/lang/sr_YU.txt
git add   data/lang/sv.txt
git add   data/lang/sv_FI.txt
git add   data/lang/sw.txt
git add   data/lang/swc.txt
git add   data/lang/ta.txt
git add   data/lang/te.txt
git add   data/lang/teo.txt
git add   data/lang/th.txt
git add   data/lang/th_TH.txt
git add   data/lang/th_TH_TRADITIONAL.txt
git add   data/lang/ti.txt
git add   data/lang/tl.txt
git add   data/lang/tl_PH.txt
git add   data/lang/to.txt
git add   data/lang/tr.txt
git add   data/lang/twq.txt
git add   data/lang/tzm.txt
git add   data/lang/tzm_Latn.txt
git add   data/lang/tzm_Latn_MA.txt
git add   data/lang/tzm_MA.txt
git add   data/lang/uk.txt
git add   data/lang/ur.txt
git add   data/lang/uz.txt
git add   data/lang/uz_AF.txt
git add   data/lang/uz_Arab.txt
git add   data/lang/uz_Arab_AF.txt
git add   data/lang/uz_Cyrl.txt
git add   data/lang/uz_Cyrl_UZ.txt
git add   data/lang/uz_Latn.txt
git add   data/lang/uz_UZ.txt
git add   data/lang/vai.txt
git add   data/lang/vai_LR.txt
git add   data/lang/vai_Latn.txt
git add   data/lang/vai_Vaii.txt
git add   data/lang/vai_Vaii_LR.txt
git add   data/lang/vi.txt
git add   data/lang/vun.txt
git add   data/lang/xog.txt
git add   data/lang/yav.txt
git add   data/lang/yo.txt
git add   data/lang/zh.txt
git add   data/lang/zh_CN.txt
git add   data/lang/zh_HK.txt
git add   data/lang/zh_Hans.txt
git add   data/lang/zh_Hans_CN.txt
git add   data/lang/zh_Hans_HK.txt
git add   data/lang/zh_Hans_MO.txt
git add   data/lang/zh_Hans_SG.txt
git add   data/lang/zh_Hant.txt
git add   data/lang/zh_Hant_HK.txt
git add   data/lang/zh_Hant_MO.txt
git add   data/lang/zh_Hant_TW.txt
git add   data/lang/zh_MO.txt
git add   data/lang/zh_SG.txt
git add   data/lang/zh_TW.txt
git add   data/lang/zu.txt
git add   data/locales/af.txt
git add   data/locales/af_NA.txt
git add   data/locales/af_ZA.txt
git add   data/locales/agq.txt
git add   data/locales/agq_CM.txt
git add   data/locales/ak.txt
git add   data/locales/ak_GH.txt
git add   data/locales/am.txt
git add   data/locales/am_ET.txt
git add   data/locales/ar.txt
git add   data/locales/ar_001.txt
git add   data/locales/ar_AE.txt
git add   data/locales/ar_BH.txt
git add   data/locales/ar_DJ.txt
git add   data/locales/ar_DZ.txt
git add   data/locales/ar_EG.txt
git add   data/locales/ar_EH.txt
git add   data/locales/ar_ER.txt
git add   data/locales/ar_IL.txt
git add   data/locales/ar_IQ.txt
git add   data/locales/ar_JO.txt
git add   data/locales/ar_KM.txt
git add   data/locales/ar_KW.txt
git add   data/locales/ar_LB.txt
git add   data/locales/ar_LY.txt
git add   data/locales/ar_MA.txt
git add   data/locales/ar_MR.txt
git add   data/locales/ar_OM.txt
git add   data/locales/ar_PS.txt
git add   data/locales/ar_QA.txt
git add   data/locales/ar_SA.txt
git add   data/locales/ar_SD.txt
git add   data/locales/ar_SO.txt
git add   data/locales/ar_SY.txt
git add   data/locales/ar_TD.txt
git add   data/locales/ar_TN.txt
git add   data/locales/ar_YE.txt
git add   data/locales/as.txt
git add   data/locales/as_IN.txt
git add   data/locales/asa.txt
git add   data/locales/asa_TZ.txt
git add   data/locales/az.txt
git add   data/locales/az_AZ.txt
git add   data/locales/az_Cyrl.txt
git add   data/locales/az_Cyrl_AZ.txt
git add   data/locales/az_Latn.txt
git add   data/locales/az_Latn_AZ.txt
git add   data/locales/bas.txt
git add   data/locales/bas_CM.txt
git add   data/locales/be.txt
git add   data/locales/be_BY.txt
git add   data/locales/bem.txt
git add   data/locales/bem_ZM.txt
git add   data/locales/bez.txt
git add   data/locales/bez_TZ.txt
git add   data/locales/bg.txt
git add   data/locales/bg_BG.txt
git add   data/locales/bm.txt
git add   data/locales/bm_ML.txt
git add   data/locales/bn.txt
git add   data/locales/bn_BD.txt
git add   data/locales/bn_IN.txt
git add   data/locales/bo.txt
git add   data/locales/bo_CN.txt
git add   data/locales/bo_IN.txt
git add   data/locales/br.txt
git add   data/locales/br_FR.txt
git add   data/locales/brx.txt
git add   data/locales/brx_IN.txt
git add   data/locales/bs.txt
git add   data/locales/bs_BA.txt
git add   data/locales/bs_Cyrl.txt
git add   data/locales/bs_Cyrl_BA.txt
git add   data/locales/bs_Latn.txt
git add   data/locales/bs_Latn_BA.txt
git add   data/locales/ca.txt
git add   data/locales/ca_AD.txt
git add   data/locales/ca_ES.txt
git add   data/locales/cgg.txt
git add   data/locales/cgg_UG.txt
git add   data/locales/chr.txt
git add   data/locales/chr_US.txt
git add   data/locales/cs.txt
git add   data/locales/cs_CZ.txt
git add   data/locales/cy.txt
git add   data/locales/cy_GB.txt
git add   data/locales/da.txt
git add   data/locales/da_DK.txt
git add   data/locales/dav.txt
git add   data/locales/dav_KE.txt
git add   data/locales/de.txt
git add   data/locales/de_AT.txt
git add   data/locales/de_BE.txt
git add   data/locales/de_CH.txt
git add   data/locales/de_DE.txt
git add   data/locales/de_LI.txt
git add   data/locales/de_LU.txt
git add   data/locales/dje.txt
git add   data/locales/dje_NE.txt
git add   data/locales/dua.txt
git add   data/locales/dua_CM.txt
git add   data/locales/dyo.txt
git add   data/locales/dyo_SN.txt
git add   data/locales/dz.txt
git add   data/locales/dz_BT.txt
git add   data/locales/ebu.txt
git add   data/locales/ebu_KE.txt
git add   data/locales/ee.txt
git add   data/locales/ee_GH.txt
git add   data/locales/ee_TG.txt
git add   data/locales/el.txt
git add   data/locales/el_CY.txt
git add   data/locales/el_GR.txt
git add   data/locales/en.txt
git add   data/locales/en_150.txt
git add   data/locales/en_AG.txt
git add   data/locales/en_AS.txt
git add   data/locales/en_AU.txt
git add   data/locales/en_BB.txt
git add   data/locales/en_BE.txt
git add   data/locales/en_BM.txt
git add   data/locales/en_BS.txt
git add   data/locales/en_BW.txt
git add   data/locales/en_BZ.txt
git add   data/locales/en_CA.txt
git add   data/locales/en_CM.txt
git add   data/locales/en_DM.txt
git add   data/locales/en_FJ.txt
git add   data/locales/en_FM.txt
git add   data/locales/en_GB.txt
git add   data/locales/en_GD.txt
git add   data/locales/en_GG.txt
git add   data/locales/en_GH.txt
git add   data/locales/en_GI.txt
git add   data/locales/en_GM.txt
git add   data/locales/en_GU.txt
git add   data/locales/en_GY.txt
git add   data/locales/en_HK.txt
git add   data/locales/en_IE.txt
git add   data/locales/en_IM.txt
git add   data/locales/en_IN.txt
git add   data/locales/en_JE.txt
git add   data/locales/en_JM.txt
git add   data/locales/en_KE.txt
git add   data/locales/en_KI.txt
git add   data/locales/en_KN.txt
git add   data/locales/en_KY.txt
git add   data/locales/en_LC.txt
git add   data/locales/en_LR.txt
git add   data/locales/en_LS.txt
git add   data/locales/en_MG.txt
git add   data/locales/en_MH.txt
git add   data/locales/en_MP.txt
git add   data/locales/en_MT.txt
git add   data/locales/en_MU.txt
git add   data/locales/en_MW.txt
git add   data/locales/en_NA.txt
git add   data/locales/en_NG.txt
git add   data/locales/en_NH.txt
git add   data/locales/en_NZ.txt
git add   data/locales/en_PG.txt
git add   data/locales/en_PH.txt
git add   data/locales/en_PK.txt
git add   data/locales/en_PR.txt
git add   data/locales/en_PW.txt
git add   data/locales/en_RH.txt
git add   data/locales/en_SB.txt
git add   data/locales/en_SC.txt
git add   data/locales/en_SG.txt
git add   data/locales/en_SL.txt
git add   data/locales/en_SS.txt
git add   data/locales/en_SZ.txt
git add   data/locales/en_TC.txt
git add   data/locales/en_TO.txt
git add   data/locales/en_TT.txt
git add   data/locales/en_TZ.txt
git add   data/locales/en_UG.txt
git add   data/locales/en_UM.txt
git add   data/locales/en_US.txt
git add   data/locales/en_US_POSIX.txt
git add   data/locales/en_VC.txt
git add   data/locales/en_VG.txt
git add   data/locales/en_VI.txt
git add   data/locales/en_VU.txt
git add   data/locales/en_WS.txt
git add   data/locales/en_ZA.txt
git add   data/locales/en_ZM.txt
git add   data/locales/en_ZW.txt
git add   data/locales/eo.txt
git add   data/locales/es.txt
git add   data/locales/es_419.txt
git add   data/locales/es_AR.txt
git add   data/locales/es_BO.txt
git add   data/locales/es_CL.txt
git add   data/locales/es_CO.txt
git add   data/locales/es_CR.txt
git add   data/locales/es_CU.txt
git add   data/locales/es_DO.txt
git add   data/locales/es_EA.txt
git add   data/locales/es_EC.txt
git add   data/locales/es_ES.txt
git add   data/locales/es_GQ.txt
git add   data/locales/es_GT.txt
git add   data/locales/es_HN.txt
git add   data/locales/es_IC.txt
git add   data/locales/es_MX.txt
git add   data/locales/es_NI.txt
git add   data/locales/es_PA.txt
git add   data/locales/es_PE.txt
git add   data/locales/es_PH.txt
git add   data/locales/es_PR.txt
git add   data/locales/es_PY.txt
git add   data/locales/es_SV.txt
git add   data/locales/es_US.txt
git add   data/locales/es_UY.txt
git add   data/locales/es_VE.txt
git add   data/locales/et.txt
git add   data/locales/et_EE.txt
git add   data/locales/eu.txt
git add   data/locales/eu_ES.txt
git add   data/locales/ewo.txt
git add   data/locales/ewo_CM.txt
git add   data/locales/fa.txt
git add   data/locales/fa_AF.txt
git add   data/locales/fa_IR.txt
git add   data/locales/ff.txt
git add   data/locales/ff_SN.txt
git add   data/locales/fi.txt
git add   data/locales/fi_FI.txt
git add   data/locales/fil.txt
git add   data/locales/fil_PH.txt
git add   data/locales/fo.txt
git add   data/locales/fo_FO.txt
git add   data/locales/fr.txt
git add   data/locales/fr_BE.txt
git add   data/locales/fr_BF.txt
git add   data/locales/fr_BI.txt
git add   data/locales/fr_BJ.txt
git add   data/locales/fr_BL.txt
git add   data/locales/fr_CA.txt
git add   data/locales/fr_CD.txt
git add   data/locales/fr_CF.txt
git add   data/locales/fr_CG.txt
git add   data/locales/fr_CH.txt
git add   data/locales/fr_CI.txt
git add   data/locales/fr_CM.txt
git add   data/locales/fr_DJ.txt
git add   data/locales/fr_DZ.txt
git add   data/locales/fr_FR.txt
git add   data/locales/fr_GA.txt
git add   data/locales/fr_GF.txt
git add   data/locales/fr_GN.txt
git add   data/locales/fr_GP.txt
git add   data/locales/fr_GQ.txt
git add   data/locales/fr_HT.txt
git add   data/locales/fr_KM.txt
git add   data/locales/fr_LU.txt
git add   data/locales/fr_MA.txt
git add   data/locales/fr_MC.txt
git add   data/locales/fr_MF.txt
git add   data/locales/fr_MG.txt
git add   data/locales/fr_ML.txt
git add   data/locales/fr_MQ.txt
git add   data/locales/fr_MR.txt
git add   data/locales/fr_MU.txt
git add   data/locales/fr_NC.txt
git add   data/locales/fr_NE.txt
git add   data/locales/fr_PF.txt
git add   data/locales/fr_RE.txt
git add   data/locales/fr_RW.txt
git add   data/locales/fr_SC.txt
git add   data/locales/fr_SN.txt
git add   data/locales/fr_SY.txt
git add   data/locales/fr_TD.txt
git add   data/locales/fr_TG.txt
git add   data/locales/fr_TN.txt
git add   data/locales/fr_VU.txt
git add   data/locales/fr_YT.txt
git add   data/locales/ga.txt
git add   data/locales/ga_IE.txt
git add   data/locales/gl.txt
git add   data/locales/gl_ES.txt
git add   data/locales/gsw.txt
git add   data/locales/gsw_CH.txt
git add   data/locales/gu.txt
git add   data/locales/gu_IN.txt
git add   data/locales/guz.txt
git add   data/locales/guz_KE.txt
git add   data/locales/gv.txt
git add   data/locales/gv_GB.txt
git add   data/locales/ha.txt
git add   data/locales/ha_GH.txt
git add   data/locales/ha_Latn.txt
git add   data/locales/ha_Latn_GH.txt
git add   data/locales/ha_Latn_NE.txt
git add   data/locales/ha_Latn_NG.txt
git add   data/locales/ha_NE.txt
git add   data/locales/ha_NG.txt
git add   data/locales/haw.txt
git add   data/locales/haw_US.txt
git add   data/locales/he.txt
git add   data/locales/he_IL.txt
git add   data/locales/hi.txt
git add   data/locales/hi_IN.txt
git add   data/locales/hr.txt
git add   data/locales/hr_BA.txt
git add   data/locales/hr_HR.txt
git add   data/locales/hu.txt
git add   data/locales/hu_HU.txt
git add   data/locales/hy.txt
git add   data/locales/hy_AM.txt
git add   data/locales/id.txt
git add   data/locales/id_ID.txt
git add   data/locales/ig.txt
git add   data/locales/ig_NG.txt
git add   data/locales/ii.txt
git add   data/locales/ii_CN.txt
git add   data/locales/in.txt
git add   data/locales/in_ID.txt
git add   data/locales/is.txt
git add   data/locales/is_IS.txt
git add   data/locales/it.txt
git add   data/locales/it_CH.txt
git add   data/locales/it_IT.txt
git add   data/locales/it_SM.txt
git add   data/locales/iw.txt
git add   data/locales/iw_IL.txt
git add   data/locales/ja.txt
git add   data/locales/ja_JP.txt
git add   data/locales/ja_JP_TRADITIONAL.txt
git add   data/locales/jgo.txt
git add   data/locales/jgo_CM.txt
git add   data/locales/jmc.txt
git add   data/locales/jmc_TZ.txt
git add   data/locales/ka.txt
git add   data/locales/ka_GE.txt
git add   data/locales/kab.txt
git add   data/locales/kab_DZ.txt
git add   data/locales/kam.txt
git add   data/locales/kam_KE.txt
git add   data/locales/kde.txt
git add   data/locales/kde_TZ.txt
git add   data/locales/kea.txt
git add   data/locales/kea_CV.txt
git add   data/locales/khq.txt
git add   data/locales/khq_ML.txt
git add   data/locales/ki.txt
git add   data/locales/ki_KE.txt
git add   data/locales/kk.txt
git add   data/locales/kk_Cyrl.txt
git add   data/locales/kk_Cyrl_KZ.txt
git add   data/locales/kk_KZ.txt
git add   data/locales/kl.txt
git add   data/locales/kl_GL.txt
git add   data/locales/kln.txt
git add   data/locales/kln_KE.txt
git add   data/locales/km.txt
git add   data/locales/km_KH.txt
git add   data/locales/kn.txt
git add   data/locales/kn_IN.txt
git add   data/locales/ko.txt
git add   data/locales/ko_KP.txt
git add   data/locales/ko_KR.txt
git add   data/locales/kok.txt
git add   data/locales/kok_IN.txt
git add   data/locales/ks.txt
git add   data/locales/ks_Arab.txt
git add   data/locales/ks_Arab_IN.txt
git add   data/locales/ks_IN.txt
git add   data/locales/ksb.txt
git add   data/locales/ksb_TZ.txt
git add   data/locales/ksf.txt
git add   data/locales/ksf_CM.txt
git add   data/locales/kw.txt
git add   data/locales/kw_GB.txt
git add   data/locales/lag.txt
git add   data/locales/lag_TZ.txt
git add   data/locales/lg.txt
git add   data/locales/lg_UG.txt
git add   data/locales/ln.txt
git add   data/locales/ln_AO.txt
git add   data/locales/ln_CD.txt
git add   data/locales/ln_CF.txt
git add   data/locales/ln_CG.txt
git add   data/locales/lo.txt
git add   data/locales/lo_LA.txt
git add   data/locales/lt.txt
git add   data/locales/lt_LT.txt
git add   data/locales/lu.txt
git add   data/locales/lu_CD.txt
git add   data/locales/luo.txt
git add   data/locales/luo_KE.txt
git add   data/locales/luy.txt
git add   data/locales/luy_KE.txt
git add   data/locales/lv.txt
git add   data/locales/lv_LV.txt
git add   data/locales/mas.txt
git add   data/locales/mas_KE.txt
git add   data/locales/mas_TZ.txt
git add   data/locales/mer.txt
git add   data/locales/mer_KE.txt
git add   data/locales/mfe.txt
git add   data/locales/mfe_MU.txt
git add   data/locales/mg.txt
git add   data/locales/mg_MG.txt
git add   data/locales/mgh.txt
git add   data/locales/mgh_MZ.txt
git add   data/locales/mgo.txt
git add   data/locales/mgo_CM.txt
git add   data/locales/mk.txt
git add   data/locales/mk_MK.txt
git add   data/locales/ml.txt
git add   data/locales/ml_IN.txt
git add   data/locales/mo.txt
git add   data/locales/mr.txt
git add   data/locales/mr_IN.txt
git add   data/locales/ms.txt
git add   data/locales/ms_BN.txt
git add   data/locales/ms_MY.txt
git add   data/locales/ms_SG.txt
git add   data/locales/mt.txt
git add   data/locales/mt_MT.txt
git add   data/locales/mua.txt
git add   data/locales/mua_CM.txt
git add   data/locales/my.txt
git add   data/locales/my_MM.txt
git add   data/locales/naq.txt
git add   data/locales/naq_NA.txt
git add   data/locales/nb.txt
git add   data/locales/nb_NO.txt
git add   data/locales/nd.txt
git add   data/locales/nd_ZW.txt
git add   data/locales/ne.txt
git add   data/locales/ne_IN.txt
git add   data/locales/ne_NP.txt
git add   data/locales/nl.txt
git add   data/locales/nl_AW.txt
git add   data/locales/nl_BE.txt
git add   data/locales/nl_CW.txt
git add   data/locales/nl_NL.txt
git add   data/locales/nl_SR.txt
git add   data/locales/nl_SX.txt
git add   data/locales/nmg.txt
git add   data/locales/nmg_CM.txt
git add   data/locales/nn.txt
git add   data/locales/nn_NO.txt
git add   data/locales/no.txt
git add   data/locales/no_NO.txt
git add   data/locales/no_NO_NY.txt
git add   data/locales/nus.txt
git add   data/locales/nus_SD.txt
git add   data/locales/nyn.txt
git add   data/locales/nyn_UG.txt
git add   data/locales/om.txt
git add   data/locales/om_ET.txt
git add   data/locales/om_KE.txt
git add   data/locales/or.txt
git add   data/locales/or_IN.txt
git add   data/locales/pa.txt
git add   data/locales/pa_Arab.txt
git add   data/locales/pa_Arab_PK.txt
git add   data/locales/pa_Guru.txt
git add   data/locales/pa_Guru_IN.txt
git add   data/locales/pa_IN.txt
git add   data/locales/pa_PK.txt
git add   data/locales/pl.txt
git add   data/locales/pl_PL.txt
git add   data/locales/pool.res
git add   data/locales/ps.txt
git add   data/locales/ps_AF.txt
git add   data/locales/pt.txt
git add   data/locales/pt_AO.txt
git add   data/locales/pt_BR.txt
git add   data/locales/pt_CV.txt
git add   data/locales/pt_GW.txt
git add   data/locales/pt_MO.txt
git add   data/locales/pt_MZ.txt
git add   data/locales/pt_PT.txt
git add   data/locales/pt_ST.txt
git add   data/locales/pt_TL.txt
git add   data/locales/resfiles.mk
git add   data/locales/rm.txt
git add   data/locales/rm_CH.txt
git add   data/locales/rn.txt
git add   data/locales/rn_BI.txt
git add   data/locales/ro.txt
git add   data/locales/ro_MD.txt
git add   data/locales/ro_RO.txt
git add   data/locales/rof.txt
git add   data/locales/rof_TZ.txt
git add   data/locales/root.txt
git add   data/locales/ru.txt
git add   data/locales/ru_BY.txt
git add   data/locales/ru_KG.txt
git add   data/locales/ru_KZ.txt
git add   data/locales/ru_MD.txt
git add   data/locales/ru_RU.txt
git add   data/locales/ru_UA.txt
git add   data/locales/rw.txt
git add   data/locales/rw_RW.txt
git add   data/locales/rwk.txt
git add   data/locales/rwk_TZ.txt
git add   data/locales/saq.txt
git add   data/locales/saq_KE.txt
git add   data/locales/sbp.txt
git add   data/locales/sbp_TZ.txt
git add   data/locales/seh.txt
git add   data/locales/seh_MZ.txt
git add   data/locales/ses.txt
git add   data/locales/ses_ML.txt
git add   data/locales/sg.txt
git add   data/locales/sg_CF.txt
git add   data/locales/sh.txt
git add   data/locales/sh_BA.txt
git add   data/locales/sh_CS.txt
git add   data/locales/sh_YU.txt
git add   data/locales/shi.txt
git add   data/locales/shi_Latn.txt
git add   data/locales/shi_Latn_MA.txt
git add   data/locales/shi_MA.txt
git add   data/locales/shi_Tfng.txt
git add   data/locales/shi_Tfng_MA.txt
git add   data/locales/si.txt
git add   data/locales/si_LK.txt
git add   data/locales/sk.txt
git add   data/locales/sk_SK.txt
git add   data/locales/sl.txt
git add   data/locales/sl_SI.txt
git add   data/locales/sn.txt
git add   data/locales/sn_ZW.txt
git add   data/locales/so.txt
git add   data/locales/so_DJ.txt
git add   data/locales/so_ET.txt
git add   data/locales/so_KE.txt
git add   data/locales/so_SO.txt
git add   data/locales/sq.txt
git add   data/locales/sq_AL.txt
git add   data/locales/sq_MK.txt
git add   data/locales/sr.txt
git add   data/locales/sr_BA.txt
git add   data/locales/sr_CS.txt
git add   data/locales/sr_Cyrl.txt
git add   data/locales/sr_Cyrl_BA.txt
git add   data/locales/sr_Cyrl_CS.txt
git add   data/locales/sr_Cyrl_ME.txt
git add   data/locales/sr_Cyrl_RS.txt
git add   data/locales/sr_Cyrl_YU.txt
git add   data/locales/sr_Latn.txt
git add   data/locales/sr_Latn_BA.txt
git add   data/locales/sr_Latn_CS.txt
git add   data/locales/sr_Latn_ME.txt
git add   data/locales/sr_Latn_RS.txt
git add   data/locales/sr_Latn_YU.txt
git add   data/locales/sr_ME.txt
git add   data/locales/sr_RS.txt
git add   data/locales/sr_YU.txt
git add   data/locales/sv.txt
git add   data/locales/sv_AX.txt
git add   data/locales/sv_FI.txt
git add   data/locales/sv_SE.txt
git add   data/locales/sw.txt
git add   data/locales/sw_KE.txt
git add   data/locales/sw_TZ.txt
git add   data/locales/sw_UG.txt
git add   data/locales/swc.txt
git add   data/locales/swc_CD.txt
git add   data/locales/ta.txt
git add   data/locales/ta_IN.txt
git add   data/locales/ta_LK.txt
git add   data/locales/ta_MY.txt
git add   data/locales/ta_SG.txt
git add   data/locales/te.txt
git add   data/locales/te_IN.txt
git add   data/locales/teo.txt
git add   data/locales/teo_KE.txt
git add   data/locales/teo_UG.txt
git add   data/locales/th.txt
git add   data/locales/th_TH.txt
git add   data/locales/th_TH_TRADITIONAL.txt
git add   data/locales/ti.txt
git add   data/locales/ti_ER.txt
git add   data/locales/ti_ET.txt
git add   data/locales/tl.txt
git add   data/locales/tl_PH.txt
git add   data/locales/to.txt
git add   data/locales/to_TO.txt
git add   data/locales/tr.txt
git add   data/locales/tr_CY.txt
git add   data/locales/tr_TR.txt
git add   data/locales/twq.txt
git add   data/locales/twq_NE.txt
git add   data/locales/tzm.txt
git add   data/locales/tzm_Latn.txt
git add   data/locales/tzm_Latn_MA.txt
git add   data/locales/tzm_MA.txt
git add   data/locales/uk.txt
git add   data/locales/uk_UA.txt
git add   data/locales/ur.txt
git add   data/locales/ur_IN.txt
git add   data/locales/ur_PK.txt
git add   data/locales/uz.txt
git add   data/locales/uz_AF.txt
git add   data/locales/uz_Arab.txt
git add   data/locales/uz_Arab_AF.txt
git add   data/locales/uz_Cyrl.txt
git add   data/locales/uz_Cyrl_UZ.txt
git add   data/locales/uz_Latn.txt
git add   data/locales/uz_Latn_UZ.txt
git add   data/locales/uz_UZ.txt
git add   data/locales/vai.txt
git add   data/locales/vai_LR.txt
git add   data/locales/vai_Latn.txt
git add   data/locales/vai_Latn_LR.txt
git add   data/locales/vai_Vaii.txt
git add   data/locales/vai_Vaii_LR.txt
git add   data/locales/vi.txt
git add   data/locales/vi_VN.txt
git add   data/locales/vun.txt
git add   data/locales/vun_TZ.txt
git add   data/locales/xog.txt
git add   data/locales/xog_UG.txt
git add   data/locales/yav.txt
git add   data/locales/yav_CM.txt
git add   data/locales/yo.txt
git add   data/locales/yo_NG.txt
git add   data/locales/zh.txt
git add   data/locales/zh_CN.txt
git add   data/locales/zh_HK.txt
git add   data/locales/zh_Hans.txt
git add   data/locales/zh_Hans_CN.txt
git add   data/locales/zh_Hans_HK.txt
git add   data/locales/zh_Hans_MO.txt
git add   data/locales/zh_Hans_SG.txt
git add   data/locales/zh_Hant.txt
git add   data/locales/zh_Hant_HK.txt
git add   data/locales/zh_Hant_MO.txt
git add   data/locales/zh_Hant_TW.txt
git add   data/locales/zh_MO.txt
git add   data/locales/zh_SG.txt
git add   data/locales/zh_TW.txt
git add   data/locales/zu.txt
git add   data/locales/zu_ZA.txt
git add   data/makedata.mak
git add   data/mappings/convrtrs.txt
git rm data/mappings/docomo-shift_jis-2007.ucm
git add   data/mappings/ibm-1026_P100-1995.ucm
git add   data/mappings/ibm-1155_P100-1999.ucm
git rm data/mappings/kddi-shift_jis-2007.ucm
git rm data/mappings/softbank-shift_jis-2007.ucm
git add   data/mappings/ucmfiles.mk
git add   data/mappings/windows-936-2000.ucm
git add   data/mappings/windows-949-2000.ucm
git add   data/mappings/windows-950-2000.ucm
git add   data/misc/currencyNumericCodes.txt
git add   data/misc/dayPeriods.txt
git add   data/misc/genderList.txt
git add   data/misc/icuver.txt
git add   data/misc/keyTypeData.txt
git add   data/misc/likelySubtags.txt
git add   data/misc/metaZones.txt
git add   data/misc/metadata.txt
git add   data/misc/numberingSystems.txt
git add   data/misc/plurals.txt
git add   data/misc/postalCodeData.txt
git add   data/misc/supplementalData.txt
git add   data/misc/timezoneTypes.txt
git add   data/misc/windowsZones.txt
git add   data/misc/zoneinfo64.txt
git add   data/rbnf/af.txt
git add   data/rbnf/am.txt
git add   data/rbnf/ar.txt
git add   data/rbnf/az.txt
git add   data/rbnf/be.txt
git add   data/rbnf/bg.txt
git add   data/rbnf/bs.txt
git add   data/rbnf/ca.txt
git add   data/rbnf/cs.txt
git add   data/rbnf/cy.txt
git add   data/rbnf/da.txt
git add   data/rbnf/de.txt
git add   data/rbnf/ee.txt
git add   data/rbnf/el.txt
git add   data/rbnf/en.txt
git add   data/rbnf/eo.txt
git add   data/rbnf/es.txt
git add   data/rbnf/es_419.txt
git add   data/rbnf/es_AR.txt
git add   data/rbnf/es_BO.txt
git add   data/rbnf/es_CL.txt
git add   data/rbnf/es_CO.txt
git add   data/rbnf/es_CR.txt
git add   data/rbnf/es_CU.txt
git add   data/rbnf/es_DO.txt
git add   data/rbnf/es_EC.txt
git add   data/rbnf/es_GT.txt
git add   data/rbnf/es_HN.txt
git add   data/rbnf/es_MX.txt
git add   data/rbnf/es_NI.txt
git add   data/rbnf/es_PA.txt
git add   data/rbnf/es_PE.txt
git add   data/rbnf/es_PR.txt
git add   data/rbnf/es_PY.txt
git add   data/rbnf/es_SV.txt
git add   data/rbnf/es_US.txt
git add   data/rbnf/es_UY.txt
git add   data/rbnf/es_VE.txt
git add   data/rbnf/et.txt
git add   data/rbnf/fa.txt
git add   data/rbnf/fa_AF.txt
git add   data/rbnf/fi.txt
git add   data/rbnf/fil.txt
git add   data/rbnf/fo.txt
git add   data/rbnf/fr.txt
git add   data/rbnf/fr_BE.txt
git add   data/rbnf/fr_CH.txt
git add   data/rbnf/ga.txt
git add   data/rbnf/he.txt
git add   data/rbnf/hi.txt
git add   data/rbnf/hr.txt
git add   data/rbnf/hu.txt
git add   data/rbnf/hy.txt
git add   data/rbnf/id.txt
git add   data/rbnf/is.txt
git add   data/rbnf/it.txt
git add   data/rbnf/ja.txt
git add   data/rbnf/ka.txt
git add   data/rbnf/kl.txt
git add   data/rbnf/km.txt
git add   data/rbnf/ko.txt
git add   data/rbnf/lo.txt
git add   data/rbnf/lt.txt
git add   data/rbnf/lv.txt
git add   data/rbnf/mk.txt
git add   data/rbnf/ms.txt
git add   data/rbnf/mt.txt
git add   data/rbnf/nb.txt
git add   data/rbnf/nl.txt
git add   data/rbnf/nn.txt
git add   data/rbnf/pl.txt
git add   data/rbnf/pt.txt
git add   data/rbnf/pt_AO.txt
git add   data/rbnf/pt_GW.txt
git add   data/rbnf/pt_MO.txt
git add   data/rbnf/pt_MZ.txt
git add   data/rbnf/pt_PT.txt
git add   data/rbnf/pt_ST.txt
git add   data/rbnf/pt_TL.txt
git add   data/rbnf/rbnffiles.mk
git add   data/rbnf/ro.txt
git add   data/rbnf/root.txt
git add   data/rbnf/ru.txt
git add   data/rbnf/sk.txt
git add   data/rbnf/sl.txt
git add   data/rbnf/sq.txt
git add   data/rbnf/sr.txt
git add   data/rbnf/sr_Latn.txt
git add   data/rbnf/sv.txt
git add   data/rbnf/ta.txt
git add   data/rbnf/th.txt
git add   data/rbnf/tr.txt
git add   data/rbnf/uk.txt
git add   data/rbnf/vi.txt
git add   data/rbnf/zh.txt
git add   data/rbnf/zh_Hant.txt
git add   data/rbnf/zh_Hant_HK.txt
git add   data/region/af.txt
git add   data/region/agq.txt
git add   data/region/ak.txt
git add   data/region/am.txt
git add   data/region/ar.txt
git add   data/region/as.txt
git add   data/region/asa.txt
git add   data/region/az.txt
git add   data/region/az_AZ.txt
git add   data/region/az_Cyrl.txt
git add   data/region/az_Latn.txt
git add   data/region/az_Latn_AZ.txt
git add   data/region/bas.txt
git add   data/region/be.txt
git add   data/region/bem.txt
git add   data/region/bez.txt
git add   data/region/bg.txt
git add   data/region/bm.txt
git add   data/region/bn.txt
git add   data/region/bn_IN.txt
git add   data/region/bo.txt
git add   data/region/bo_IN.txt
git add   data/region/br.txt
git add   data/region/brx.txt
git add   data/region/bs.txt
git add   data/region/bs_BA.txt
git add   data/region/bs_Cyrl.txt
git add   data/region/bs_Latn.txt
git add   data/region/bs_Latn_BA.txt
git add   data/region/ca.txt
git add   data/region/cgg.txt
git add   data/region/chr.txt
git add   data/region/cs.txt
git add   data/region/cy.txt
git add   data/region/da.txt
git add   data/region/dav.txt
git add   data/region/de.txt
git add   data/region/de_CH.txt
git add   data/region/dje.txt
git add   data/region/dua.txt
git add   data/region/dyo.txt
git add   data/region/dz.txt
git add   data/region/ebu.txt
git add   data/region/ee.txt
git add   data/region/el.txt
git add   data/region/en.txt
git add   data/region/en_GB.txt
git add   data/region/en_NH.txt
git add   data/region/en_RH.txt
git add   data/region/en_VU.txt
git add   data/region/en_ZW.txt
git add   data/region/eo.txt
git add   data/region/es.txt
git add   data/region/es_CL.txt
git add   data/region/et.txt
git add   data/region/eu.txt
git add   data/region/ewo.txt
git add   data/region/fa.txt
git add   data/region/fa_AF.txt
git add   data/region/ff.txt
git add   data/region/fi.txt
git add   data/region/fil.txt
git add   data/region/fil_PH.txt
git add   data/region/fo.txt
git add   data/region/fr.txt
git add   data/region/fr_CA.txt
git add   data/region/ga.txt
git add   data/region/gl.txt
git add   data/region/gsw.txt
git add   data/region/gu.txt
git add   data/region/guz.txt
git add   data/region/gv.txt
git add   data/region/ha.txt
git add   data/region/ha_GH.txt
git add   data/region/ha_Latn.txt
git add   data/region/ha_Latn_GH.txt
git add   data/region/ha_Latn_NE.txt
git add   data/region/ha_Latn_NG.txt
git add   data/region/ha_NE.txt
git add   data/region/ha_NG.txt
git add   data/region/haw.txt
git add   data/region/he.txt
git add   data/region/he_IL.txt
git add   data/region/hi.txt
git add   data/region/hr.txt
git add   data/region/hu.txt
git add   data/region/hy.txt
git add   data/region/id.txt
git add   data/region/id_ID.txt
git add   data/region/ig.txt
git add   data/region/ii.txt
git add   data/region/in.txt
git add   data/region/in_ID.txt
git add   data/region/is.txt
git add   data/region/it.txt
git add   data/region/iw.txt
git add   data/region/iw_IL.txt
git add   data/region/ja.txt
git add   data/region/ja_JP.txt
git add   data/region/ja_JP_TRADITIONAL.txt
git add   data/region/jgo.txt
git add   data/region/jmc.txt
git add   data/region/ka.txt
git add   data/region/kab.txt
git add   data/region/kam.txt
git add   data/region/kde.txt
git add   data/region/kea.txt
git add   data/region/khq.txt
git add   data/region/ki.txt
git add   data/region/kk.txt
git add   data/region/kk_Cyrl.txt
git add   data/region/kk_Cyrl_KZ.txt
git add   data/region/kk_KZ.txt
git add   data/region/kl.txt
git add   data/region/kln.txt
git add   data/region/km.txt
git add   data/region/kn.txt
git add   data/region/ko.txt
git add   data/region/kok.txt
git add   data/region/ks.txt
git add   data/region/ks_Arab.txt
git add   data/region/ks_Arab_IN.txt
git add   data/region/ks_IN.txt
git add   data/region/ksb.txt
git add   data/region/ksf.txt
git add   data/region/kw.txt
git add   data/region/lag.txt
git add   data/region/lg.txt
git add   data/region/ln.txt
git add   data/region/lo.txt
git add   data/region/lt.txt
git add   data/region/lu.txt
git add   data/region/luo.txt
git add   data/region/luy.txt
git add   data/region/lv.txt
git add   data/region/mas.txt
git add   data/region/mer.txt
git add   data/region/mfe.txt
git add   data/region/mg.txt
git add   data/region/mgh.txt
git add   data/region/mgo.txt
git add   data/region/mk.txt
git add   data/region/ml.txt
git add   data/region/mo.txt
git add   data/region/mr.txt
git add   data/region/ms.txt
git add   data/region/mt.txt
git add   data/region/mua.txt
git add   data/region/my.txt
git add   data/region/naq.txt
git add   data/region/nb.txt
git add   data/region/nb_NO.txt
git add   data/region/nd.txt
git add   data/region/ne.txt
git add   data/region/nl.txt
git add   data/region/nl_BE.txt
git add   data/region/nmg.txt
git add   data/region/nn.txt
git add   data/region/nn_NO.txt
git add   data/region/no.txt
git add   data/region/no_NO.txt
git add   data/region/no_NO_NY.txt
git add   data/region/nus.txt
git add   data/region/nyn.txt
git add   data/region/om.txt
git add   data/region/or.txt
git add   data/region/pa.txt
git add   data/region/pa_Arab.txt
git add   data/region/pa_Arab_PK.txt
git add   data/region/pa_Guru.txt
git add   data/region/pa_Guru_IN.txt
git add   data/region/pa_IN.txt
git add   data/region/pa_PK.txt
git add   data/region/pl.txt
git add   data/region/pool.res
git add   data/region/ps.txt
git add   data/region/pt.txt
git add   data/region/pt_PT.txt
git add   data/region/resfiles.mk
git add   data/region/rm.txt
git add   data/region/rn.txt
git add   data/region/ro.txt
git add   data/region/ro_MD.txt
git add   data/region/rof.txt
git add   data/region/root.txt
git add   data/region/ru.txt
git add   data/region/rw.txt
git add   data/region/rwk.txt
git add   data/region/saq.txt
git add   data/region/sbp.txt
git add   data/region/seh.txt
git add   data/region/ses.txt
git add   data/region/sg.txt
git add   data/region/sh.txt
git add   data/region/sh_BA.txt
git add   data/region/sh_CS.txt
git add   data/region/sh_YU.txt
git add   data/region/shi.txt
git add   data/region/shi_Latn.txt
git rm data/region/shi_Latn_MA.txt
git add   data/region/shi_MA.txt
git add   data/region/shi_Tfng.txt
git add   data/region/si.txt
git add   data/region/sk.txt
git add   data/region/sl.txt
git add   data/region/sn.txt
git add   data/region/so.txt
git add   data/region/sq.txt
git add   data/region/sr.txt
git add   data/region/sr_BA.txt
git add   data/region/sr_CS.txt
git add   data/region/sr_Cyrl.txt
git add   data/region/sr_Cyrl_BA.txt
git add   data/region/sr_Cyrl_CS.txt
git add   data/region/sr_Cyrl_RS.txt
git add   data/region/sr_Cyrl_YU.txt
git add   data/region/sr_Latn.txt
git add   data/region/sr_Latn_BA.txt
git add   data/region/sr_Latn_CS.txt
git add   data/region/sr_Latn_ME.txt
git add   data/region/sr_Latn_RS.txt
git add   data/region/sr_Latn_YU.txt
git add   data/region/sr_ME.txt
git add   data/region/sr_RS.txt
git add   data/region/sr_YU.txt
git add   data/region/sv.txt
git add   data/region/sv_FI.txt
git add   data/region/sw.txt
git add   data/region/swc.txt
git add   data/region/ta.txt
git add   data/region/te.txt
git add   data/region/teo.txt
git add   data/region/th.txt
git add   data/region/th_TH.txt
git add   data/region/th_TH_TRADITIONAL.txt
git add   data/region/ti.txt
git add   data/region/tl.txt
git add   data/region/tl_PH.txt
git add   data/region/to.txt
git add   data/region/tr.txt
git add   data/region/twq.txt
git add   data/region/tzm.txt
git add   data/region/tzm_Latn.txt
git add   data/region/tzm_Latn_MA.txt
git add   data/region/tzm_MA.txt
git add   data/region/uk.txt
git add   data/region/ur.txt
git add   data/region/uz.txt
git add   data/region/uz_AF.txt
git add   data/region/uz_Arab.txt
git add   data/region/uz_Arab_AF.txt
git add   data/region/uz_Cyrl.txt
git add   data/region/uz_Cyrl_UZ.txt
git add   data/region/uz_Latn.txt
git add   data/region/uz_UZ.txt
git add   data/region/vai.txt
git add   data/region/vai_LR.txt
git add   data/region/vai_Latn.txt
git add   data/region/vai_Vaii.txt
git add   data/region/vai_Vaii_LR.txt
git add   data/region/vi.txt
git add   data/region/vun.txt
git add   data/region/xog.txt
git add   data/region/yav.txt
git add   data/region/yo.txt
git add   data/region/zh.txt
git add   data/region/zh_CN.txt
git add   data/region/zh_HK.txt
git add   data/region/zh_Hans.txt
git add   data/region/zh_Hans_CN.txt
git add   data/region/zh_Hans_HK.txt
git add   data/region/zh_Hans_MO.txt
git add   data/region/zh_Hans_SG.txt
git add   data/region/zh_Hant.txt
git add   data/region/zh_Hant_HK.txt
git add   data/region/zh_Hant_MO.txt
git add   data/region/zh_Hant_TW.txt
git add   data/region/zh_MO.txt
git add   data/region/zh_SG.txt
git add   data/region/zh_TW.txt
git add   data/region/zu.txt
git add   data/translit/Amharic_Latin_BGN.txt
git add   data/translit/Any_Accents.txt
git add   data/translit/Any_Publishing.txt
git add   data/translit/Arabic_Latin.txt
git add   data/translit/Arabic_Latin_BGN.txt
git add   data/translit/Armenian_Latin_BGN.txt
git add   data/translit/Azerbaijani_Latin_BGN.txt
git add   data/translit/Belarusian_Latin_BGN.txt
git add   data/translit/Bengali_Devanagari.txt
git add   data/translit/Bengali_Gujarati.txt
git add   data/translit/Bengali_Gurmukhi.txt
git add   data/translit/Bengali_InterIndic.txt
git add   data/translit/Bengali_Kannada.txt
git add   data/translit/Bengali_Latin.txt
git add   data/translit/Bengali_Malayalam.txt
git add   data/translit/Bengali_Oriya.txt
git add   data/translit/Bengali_Tamil.txt
git add   data/translit/Bengali_Telugu.txt
git add   data/translit/Bulgarian_Latin_BGN.txt
git add   data/translit/Cyrillic_Latin.txt
git add   data/translit/Devanagari_Bengali.txt
git add   data/translit/Devanagari_Gujarati.txt
git add   data/translit/Devanagari_Gurmukhi.txt
git add   data/translit/Devanagari_InterIndic.txt
git add   data/translit/Devanagari_Kannada.txt
git add   data/translit/Devanagari_Latin.txt
git add   data/translit/Devanagari_Malayalam.txt
git add   data/translit/Devanagari_Oriya.txt
git add   data/translit/Devanagari_Tamil.txt
git add   data/translit/Devanagari_Telugu.txt
git add   data/translit/Fullwidth_Halfwidth.txt
git add   data/translit/Georgian_Latin.txt
git add   data/translit/Georgian_Latin_BGN.txt
git add   data/translit/Greek_Latin.txt
git add   data/translit/Greek_Latin_BGN.txt
git add   data/translit/Greek_Latin_UNGEGN.txt
git add   data/translit/Gujarati_Bengali.txt
git add   data/translit/Gujarati_Devanagari.txt
git add   data/translit/Gujarati_Gurmukhi.txt
git add   data/translit/Gujarati_InterIndic.txt
git add   data/translit/Gujarati_Kannada.txt
git add   data/translit/Gujarati_Latin.txt
git add   data/translit/Gujarati_Malayalam.txt
git add   data/translit/Gujarati_Oriya.txt
git add   data/translit/Gujarati_Tamil.txt
git add   data/translit/Gujarati_Telugu.txt
git add   data/translit/Gurmukhi_Bengali.txt
git add   data/translit/Gurmukhi_Devanagari.txt
git add   data/translit/Gurmukhi_Gujarati.txt
git add   data/translit/Gurmukhi_InterIndic.txt
git add   data/translit/Gurmukhi_Kannada.txt
git add   data/translit/Gurmukhi_Latin.txt
git add   data/translit/Gurmukhi_Malayalam.txt
git add   data/translit/Gurmukhi_Oriya.txt
git add   data/translit/Gurmukhi_Tamil.txt
git add   data/translit/Gurmukhi_Telugu.txt
git add   data/translit/Han_Latin.txt
git add   data/translit/Han_Latin_Names.txt
git add   data/translit/Han_Spacedhan.txt
git add   data/translit/Hangul_Latin.txt
git add   data/translit/Hebrew_Latin.txt
git add   data/translit/Hebrew_Latin_BGN.txt
git add   data/translit/Hiragana_Katakana.txt
git add   data/translit/Hiragana_Latin.txt
git add   data/translit/IPA_XSampa.txt
git add   data/translit/InterIndic_Bengali.txt
git add   data/translit/InterIndic_Devanagari.txt
git add   data/translit/InterIndic_Gujarati.txt
git add   data/translit/InterIndic_Gurmukhi.txt
git add   data/translit/InterIndic_Kannada.txt
git add   data/translit/InterIndic_Latin.txt
git add   data/translit/InterIndic_Malayalam.txt
git add   data/translit/InterIndic_Oriya.txt
git add   data/translit/InterIndic_Tamil.txt
git add   data/translit/InterIndic_Telugu.txt
git add   data/translit/Jamo_Latin.txt
git add   data/translit/JapaneseKana_Latin_BGN.txt
git add   data/translit/Kannada_Bengali.txt
git add   data/translit/Kannada_Devanagari.txt
git add   data/translit/Kannada_Gujarati.txt
git add   data/translit/Kannada_Gurmukhi.txt
git add   data/translit/Kannada_InterIndic.txt
git add   data/translit/Kannada_Latin.txt
git add   data/translit/Kannada_Malayalam.txt
git add   data/translit/Kannada_Oriya.txt
git add   data/translit/Kannada_Tamil.txt
git add   data/translit/Kannada_Telugu.txt
git add   data/translit/Kazakh_Latin_BGN.txt
git add   data/translit/Kirghiz_Latin_BGN.txt
git add   data/translit/Korean_Latin_BGN.txt
git add   data/translit/Latin_ASCII.txt
git add   data/translit/Latin_Armenian.txt
git add   data/translit/Latin_Bengali.txt
git add   data/translit/Latin_Bopomofo.txt
git add   data/translit/Latin_ConjoiningJamo.txt
git add   data/translit/Latin_Devanagari.txt
git add   data/translit/Latin_Gujarati.txt
git add   data/translit/Latin_Gurmukhi.txt
git add   data/translit/Latin_Hangul.txt
git add   data/translit/Latin_InterIndic.txt
git add   data/translit/Latin_Jamo.txt
git add   data/translit/Latin_Kannada.txt
git add   data/translit/Latin_Katakana.txt
git add   data/translit/Latin_Malayalam.txt
git add   data/translit/Latin_NumericPinyin.txt
git add   data/translit/Latin_Oriya.txt
git add   data/translit/Latin_Tamil.txt
git add   data/translit/Latin_Telugu.txt
git add   data/translit/Latin_Thaana.txt
git add   data/translit/Latin_Thai.txt
git add   data/translit/Macedonian_Latin_BGN.txt
git add   data/translit/Malayalam_Bengali.txt
git add   data/translit/Malayalam_Devanagari.txt
git add   data/translit/Malayalam_Gujarati.txt
git add   data/translit/Malayalam_Gurmukhi.txt
git add   data/translit/Malayalam_InterIndic.txt
git add   data/translit/Malayalam_Kannada.txt
git add   data/translit/Malayalam_Latin.txt
git add   data/translit/Malayalam_Oriya.txt
git add   data/translit/Malayalam_Tamil.txt
git add   data/translit/Malayalam_Telugu.txt
git add   data/translit/Maldivian_Latin_BGN.txt
git add   data/translit/Mongolian_Latin_BGN.txt
git add   data/translit/Oriya_Bengali.txt
git add   data/translit/Oriya_Devanagari.txt
git add   data/translit/Oriya_Gujarati.txt
git add   data/translit/Oriya_Gurmukhi.txt
git add   data/translit/Oriya_InterIndic.txt
git add   data/translit/Oriya_Kannada.txt
git add   data/translit/Oriya_Latin.txt
git add   data/translit/Oriya_Malayalam.txt
git add   data/translit/Oriya_Tamil.txt
git add   data/translit/Oriya_Telugu.txt
git add   data/translit/Pashto_Latin_BGN.txt
git add   data/translit/Persian_Latin_BGN.txt
git add   data/translit/Pinyin_NumericPinyin.txt
git add   data/translit/Russian_Latin_BGN.txt
git add   data/translit/Serbian_Latin_BGN.txt
git add   data/translit/Simplified_Traditional.txt
git add   data/translit/Syriac_Latin.txt
git add   data/translit/Tamil_Bengali.txt
git add   data/translit/Tamil_Devanagari.txt
git add   data/translit/Tamil_Gujarati.txt
git add   data/translit/Tamil_Gurmukhi.txt
git add   data/translit/Tamil_InterIndic.txt
git add   data/translit/Tamil_Kannada.txt
git add   data/translit/Tamil_Latin.txt
git add   data/translit/Tamil_Malayalam.txt
git add   data/translit/Tamil_Oriya.txt
git add   data/translit/Tamil_Telugu.txt
git add   data/translit/Telugu_Bengali.txt
git add   data/translit/Telugu_Devanagari.txt
git add   data/translit/Telugu_Gujarati.txt
git add   data/translit/Telugu_Gurmukhi.txt
git add   data/translit/Telugu_InterIndic.txt
git add   data/translit/Telugu_Kannada.txt
git add   data/translit/Telugu_Latin.txt
git add   data/translit/Telugu_Malayalam.txt
git add   data/translit/Telugu_Oriya.txt
git add   data/translit/Telugu_Tamil.txt
git add   data/translit/ThaiLogical_Latin.txt
git add   data/translit/Thai_Latin.txt
git add   data/translit/Thai_ThaiLogical.txt
git add   data/translit/Thai_ThaiSemi.txt
git add   data/translit/Turkmen_Latin_BGN.txt
git add   data/translit/Ukrainian_Latin_BGN.txt
git add   data/translit/Uzbek_Latin_BGN.txt
git add   data/translit/cs_FONIPA_ja.txt
git add   data/translit/cs_FONIPA_ko.txt
git add   data/translit/cs_cs_FONIPA.txt
git add   data/translit/cs_ja.txt
git add   data/translit/cs_ko.txt
git add   data/translit/es_419_ja.txt
git add   data/translit/es_419_zh.txt
git add   data/translit/es_FONIPA_am.txt
git add   data/translit/es_FONIPA_es_419_FONIPA.txt
git add   data/translit/es_FONIPA_ja.txt
git add   data/translit/es_FONIPA_zh.txt
git add   data/translit/es_am.txt
git add   data/translit/es_es_FONIPA.txt
git add   data/translit/es_ja.txt
git add   data/translit/es_zh.txt
git add   data/translit/it_am.txt
git add   data/translit/it_ja.txt
git add   data/translit/ja_Latn_ko.txt
git add   data/translit/ja_Latn_ru.txt
git add   data/translit/pl_FONIPA_ja.txt
git add   data/translit/pl_ja.txt
git add   data/translit/pl_pl_FONIPA.txt
git add   data/translit/ro_FONIPA_ja.txt
git add   data/translit/ro_ja.txt
git add   data/translit/ro_ro_FONIPA.txt
git add   data/translit/root.txt
git add   data/translit/ru_ja.txt
git add   data/translit/ru_zh.txt
git add   data/translit/sk_FONIPA_ja.txt
git add   data/translit/sk_ja.txt
git add   data/translit/sk_sk_FONIPA.txt
git add   data/translit/zh_Latn_PINYIN_ru.txt
git add   data/zone/af.txt
git add   data/zone/agq.txt
git add   data/zone/ak.txt
git add   data/zone/am.txt
git add   data/zone/ar.txt
git add   data/zone/as.txt
git add   data/zone/asa.txt
git add   data/zone/az.txt
git add   data/zone/az_AZ.txt
git add   data/zone/az_Cyrl.txt
git add   data/zone/az_Latn.txt
git add   data/zone/az_Latn_AZ.txt
git add   data/zone/bas.txt
git add   data/zone/be.txt
git add   data/zone/bem.txt
git add   data/zone/bez.txt
git add   data/zone/bg.txt
git add   data/zone/bm.txt
git add   data/zone/bn.txt
git add   data/zone/bn_IN.txt
git add   data/zone/bo.txt
git add   data/zone/br.txt
git add   data/zone/brx.txt
git add   data/zone/bs.txt
git add   data/zone/bs_BA.txt
git add   data/zone/bs_Cyrl.txt
git add   data/zone/bs_Latn.txt
git add   data/zone/bs_Latn_BA.txt
git add   data/zone/ca.txt
git add   data/zone/cgg.txt
git add   data/zone/chr.txt
git add   data/zone/cs.txt
git add   data/zone/cy.txt
git add   data/zone/da.txt
git add   data/zone/dav.txt
git add   data/zone/de.txt
git add   data/zone/dje.txt
git add   data/zone/dua.txt
git add   data/zone/dyo.txt
git add   data/zone/dz.txt
git add   data/zone/ebu.txt
git add   data/zone/ee.txt
git add   data/zone/el.txt
git add   data/zone/en.txt
git add   data/zone/en_AG.txt
git add   data/zone/en_AU.txt
git add   data/zone/en_BB.txt
git add   data/zone/en_BZ.txt
git add   data/zone/en_CA.txt
git add   data/zone/en_CM.txt
git add   data/zone/en_DM.txt
git add   data/zone/en_FJ.txt
git add   data/zone/en_FM.txt
git add   data/zone/en_GB.txt
git add   data/zone/en_GD.txt
git add   data/zone/en_GH.txt
git add   data/zone/en_GM.txt
git add   data/zone/en_GU.txt
git add   data/zone/en_GY.txt
git add   data/zone/en_HK.txt
git add   data/zone/en_IE.txt
git add   data/zone/en_IN.txt
git add   data/zone/en_JM.txt
git add   data/zone/en_KE.txt
git add   data/zone/en_KI.txt
git add   data/zone/en_KN.txt
git add   data/zone/en_KY.txt
git add   data/zone/en_LC.txt
git add   data/zone/en_LR.txt
git add   data/zone/en_LS.txt
git add   data/zone/en_MG.txt
git add   data/zone/en_MH.txt
git add   data/zone/en_MP.txt
git add   data/zone/en_MU.txt
git add   data/zone/en_MW.txt
git add   data/zone/en_NA.txt
git add   data/zone/en_NG.txt
git add   data/zone/en_NH.txt
git add   data/zone/en_NZ.txt
git add   data/zone/en_PG.txt
git add   data/zone/en_PH.txt
git add   data/zone/en_PK.txt
git add   data/zone/en_PW.txt
git add   data/zone/en_RH.txt
git add   data/zone/en_SB.txt
git add   data/zone/en_SC.txt
git add   data/zone/en_SG.txt
git add   data/zone/en_SL.txt
git add   data/zone/en_SS.txt
git add   data/zone/en_SZ.txt
git add   data/zone/en_TC.txt
git add   data/zone/en_TO.txt
git add   data/zone/en_TT.txt
git add   data/zone/en_TZ.txt
git add   data/zone/en_UG.txt
git add   data/zone/en_VC.txt
git add   data/zone/en_VG.txt
git add   data/zone/en_VU.txt
git add   data/zone/en_WS.txt
git add   data/zone/en_ZA.txt
git add   data/zone/en_ZM.txt
git add   data/zone/en_ZW.txt
git add   data/zone/eo.txt
git add   data/zone/es.txt
git add   data/zone/es_419.txt
git add   data/zone/es_AR.txt
git add   data/zone/et.txt
git add   data/zone/eu.txt
git add   data/zone/ewo.txt
git add   data/zone/fa.txt
git add   data/zone/ff.txt
git add   data/zone/fi.txt
git add   data/zone/fil.txt
git add   data/zone/fil_PH.txt
git add   data/zone/fo.txt
git add   data/zone/fr.txt
git add   data/zone/fr_CA.txt
git add   data/zone/ga.txt
git add   data/zone/gl.txt
git add   data/zone/gsw.txt
git add   data/zone/gu.txt
git add   data/zone/guz.txt
git add   data/zone/gv.txt
git add   data/zone/ha.txt
git add   data/zone/ha_GH.txt
git add   data/zone/ha_Latn.txt
git add   data/zone/ha_Latn_GH.txt
git add   data/zone/ha_Latn_NE.txt
git add   data/zone/ha_Latn_NG.txt
git add   data/zone/ha_NE.txt
git add   data/zone/ha_NG.txt
git add   data/zone/haw.txt
git add   data/zone/he.txt
git add   data/zone/he_IL.txt
git add   data/zone/hi.txt
git add   data/zone/hr.txt
git add   data/zone/hu.txt
git add   data/zone/hy.txt
git add   data/zone/id.txt
git add   data/zone/id_ID.txt
git add   data/zone/ig.txt
git add   data/zone/ii.txt
git add   data/zone/in.txt
git add   data/zone/in_ID.txt
git add   data/zone/is.txt
git add   data/zone/it.txt
git add   data/zone/iw.txt
git add   data/zone/iw_IL.txt
git add   data/zone/ja.txt
git add   data/zone/ja_JP.txt
git add   data/zone/ja_JP_TRADITIONAL.txt
git add   data/zone/jgo.txt
git add   data/zone/jmc.txt
git add   data/zone/ka.txt
git add   data/zone/kab.txt
git add   data/zone/kam.txt
git add   data/zone/kde.txt
git add   data/zone/kea.txt
git add   data/zone/khq.txt
git add   data/zone/ki.txt
git add   data/zone/kk.txt
git add   data/zone/kk_Cyrl.txt
git add   data/zone/kk_Cyrl_KZ.txt
git add   data/zone/kk_KZ.txt
git add   data/zone/kl.txt
git add   data/zone/kln.txt
git add   data/zone/km.txt
git add   data/zone/kn.txt
git add   data/zone/ko.txt
git add   data/zone/ko_KP.txt
git add   data/zone/kok.txt
git add   data/zone/ks.txt
git add   data/zone/ks_Arab.txt
git add   data/zone/ks_Arab_IN.txt
git add   data/zone/ks_IN.txt
git add   data/zone/ksb.txt
git add   data/zone/ksf.txt
git add   data/zone/kw.txt
git add   data/zone/lag.txt
git add   data/zone/lg.txt
git add   data/zone/ln.txt
git add   data/zone/lo.txt
git add   data/zone/lt.txt
git add   data/zone/lu.txt
git add   data/zone/luo.txt
git add   data/zone/luy.txt
git add   data/zone/lv.txt
git add   data/zone/mas.txt
git add   data/zone/mer.txt
git add   data/zone/mfe.txt
git add   data/zone/mg.txt
git add   data/zone/mgh.txt
git add   data/zone/mgo.txt
git add   data/zone/mk.txt
git add   data/zone/ml.txt
git add   data/zone/mo.txt
git add   data/zone/mr.txt
git add   data/zone/ms.txt
git add   data/zone/mt.txt
git add   data/zone/mua.txt
git add   data/zone/my.txt
git add   data/zone/naq.txt
git add   data/zone/nb.txt
git add   data/zone/nb_NO.txt
git add   data/zone/nd.txt
git add   data/zone/ne.txt
git add   data/zone/nl.txt
git add   data/zone/nmg.txt
git add   data/zone/nn.txt
git add   data/zone/nn_NO.txt
git add   data/zone/no.txt
git add   data/zone/no_NO.txt
git add   data/zone/no_NO_NY.txt
git add   data/zone/nus.txt
git add   data/zone/nyn.txt
git add   data/zone/om.txt
git add   data/zone/or.txt
git add   data/zone/pa.txt
git add   data/zone/pa_Arab.txt
git add   data/zone/pa_Arab_PK.txt
git add   data/zone/pa_Guru.txt
git add   data/zone/pa_Guru_IN.txt
git add   data/zone/pa_IN.txt
git add   data/zone/pa_PK.txt
git add   data/zone/pl.txt
git add   data/zone/pool.res
git add   data/zone/ps.txt
git add   data/zone/pt.txt
git add   data/zone/pt_AO.txt
git add   data/zone/pt_CV.txt
git add   data/zone/pt_GW.txt
git add   data/zone/pt_MO.txt
git add   data/zone/pt_MZ.txt
git add   data/zone/pt_PT.txt
git add   data/zone/pt_ST.txt
git add   data/zone/pt_TL.txt
git add   data/zone/resfiles.mk
git add   data/zone/rm.txt
git add   data/zone/rn.txt
git add   data/zone/ro.txt
git add   data/zone/ro_MD.txt
git add   data/zone/rof.txt
git add   data/zone/root.txt
git add   data/zone/ru.txt
git add   data/zone/rw.txt
git add   data/zone/rwk.txt
git add   data/zone/saq.txt
git add   data/zone/sbp.txt
git add   data/zone/seh.txt
git add   data/zone/ses.txt
git add   data/zone/sg.txt
git add   data/zone/sh.txt
git add   data/zone/sh_BA.txt
git add   data/zone/sh_CS.txt
git add   data/zone/sh_YU.txt
git add   data/zone/shi.txt
git add   data/zone/shi_Latn.txt
git rm data/zone/shi_Latn_MA.txt
git add   data/zone/shi_MA.txt
git add   data/zone/shi_Tfng.txt
git add   data/zone/si.txt
git add   data/zone/sk.txt
git add   data/zone/sl.txt
git add   data/zone/sn.txt
git add   data/zone/so.txt
git add   data/zone/sq.txt
git add   data/zone/sr.txt
git add   data/zone/sr_BA.txt
git add   data/zone/sr_CS.txt
git add   data/zone/sr_Cyrl.txt
git add   data/zone/sr_Cyrl_BA.txt
git add   data/zone/sr_Cyrl_CS.txt
git add   data/zone/sr_Cyrl_RS.txt
git add   data/zone/sr_Cyrl_YU.txt
git add   data/zone/sr_Latn.txt
git add   data/zone/sr_Latn_BA.txt
git add   data/zone/sr_Latn_CS.txt
git add   data/zone/sr_Latn_ME.txt
git add   data/zone/sr_Latn_RS.txt
git add   data/zone/sr_Latn_YU.txt
git add   data/zone/sr_ME.txt
git add   data/zone/sr_RS.txt
git add   data/zone/sr_YU.txt
git add   data/zone/sv.txt
git add   data/zone/sv_FI.txt
git add   data/zone/sw.txt
git add   data/zone/swc.txt
git add   data/zone/ta.txt
git add   data/zone/ta_MY.txt
git add   data/zone/ta_SG.txt
git add   data/zone/te.txt
git add   data/zone/teo.txt
git add   data/zone/th.txt
git add   data/zone/th_TH.txt
git add   data/zone/th_TH_TRADITIONAL.txt
git add   data/zone/ti.txt
git add   data/zone/tl.txt
git add   data/zone/tl_PH.txt
git add   data/zone/to.txt
git add   data/zone/tr.txt
git add   data/zone/twq.txt
git add   data/zone/tzm.txt
git add   data/zone/tzm_Latn.txt
git add   data/zone/tzm_Latn_MA.txt
git add   data/zone/tzm_MA.txt
git add   data/zone/uk.txt
git add   data/zone/ur.txt
git add   data/zone/uz.txt
git add   data/zone/uz_AF.txt
git add   data/zone/uz_Arab.txt
git add   data/zone/uz_Arab_AF.txt
git add   data/zone/uz_Cyrl.txt
git add   data/zone/uz_Cyrl_UZ.txt
git add   data/zone/uz_Latn.txt
git add   data/zone/uz_UZ.txt
git add   data/zone/vai.txt
git add   data/zone/vai_LR.txt
git add   data/zone/vai_Latn.txt
git add   data/zone/vai_Vaii.txt
git add   data/zone/vai_Vaii_LR.txt
git add   data/zone/vi.txt
git add   data/zone/vun.txt
git add   data/zone/xog.txt
git add   data/zone/yav.txt
git add   data/zone/yo.txt
git add   data/zone/zh.txt
git add   data/zone/zh_CN.txt
git add   data/zone/zh_HK.txt
git add   data/zone/zh_Hans.txt
git add   data/zone/zh_Hans_CN.txt
git add   data/zone/zh_Hans_HK.txt
git add   data/zone/zh_Hans_MO.txt
git add   data/zone/zh_Hans_SG.txt
git add   data/zone/zh_Hant.txt
git add   data/zone/zh_Hant_HK.txt
git add   data/zone/zh_Hant_MO.txt
git add   data/zone/zh_Hant_TW.txt
git add   data/zone/zh_MO.txt
git add   data/zone/zh_SG.txt
git add   data/zone/zh_TW.txt
git add   data/zone/zu.txt
git add   extra/uconv/uconv.cpp
git add   i18n/Android.mk
git add   i18n/Makefile.in
git add   i18n/alphaindex.cpp
git add   i18n/basictz.cpp
git rm i18n/bms.cpp
git rm i18n/bmsearch.cpp
git add   i18n/calendar.cpp
git add   i18n/chnsecal.cpp
git add   i18n/chnsecal.h
git rm i18n/colldata.cpp
git add   i18n/decNumber.c
git add   i18n/decimfmt.cpp
git add   i18n/dtfmtsym.cpp
git add   i18n/dtptngen.cpp
git add   i18n/fpositer.cpp
git add   i18n/gender.cpp
git add   i18n/i18n.vcxproj
git add   i18n/i18n.vcxproj.filters
git add   i18n/locdspnm.cpp
git add   i18n/msgfmt.cpp
git add   i18n/numfmt.cpp
git add   i18n/olsontz.cpp
git add   i18n/olsontz.h
git add   i18n/rbtz.cpp
git add   i18n/reldtfmt.cpp
git add   i18n/simpletz.cpp
git add   i18n/smpdtfmt.cpp
git add   i18n/timezone.cpp
git add   i18n/tzfmt.cpp
git add   i18n/tzgnames.cpp
git add   i18n/tznames.cpp
git add   i18n/tznames_impl.cpp
git add   i18n/tznames_impl.h
git add   i18n/ucal.cpp
git add   i18n/ucln_in.h
git add   i18n/ucol.cpp
git add   i18n/ucurr.cpp
git add   i18n/udat.cpp
git add   i18n/ulocdata.c
git add   i18n/unicode/basictz.h
git rm i18n/unicode/bms.h
git rm i18n/unicode/bmsearch.h
git add   i18n/unicode/calendar.h
git rm i18n/unicode/colldata.h
git add   i18n/unicode/dcfmtsym.h
git add   i18n/unicode/decimfmt.h
git add   i18n/unicode/dtfmtsym.h
git add   i18n/unicode/fmtable.h
git add   i18n/unicode/fpositer.h
git add   i18n/unicode/gender.h
git add   i18n/unicode/gregocal.h
git add   i18n/unicode/locdspnm.h
git add   i18n/unicode/msgfmt.h
git add   i18n/unicode/numfmt.h
git add   i18n/unicode/numsys.h
git add   i18n/unicode/plurfmt.h
git add   i18n/unicode/plurrule.h
git add   i18n/unicode/rbnf.h
git add   i18n/unicode/rbtz.h
git add   i18n/unicode/regex.h
git add   i18n/unicode/simpletz.h
git add   i18n/unicode/smpdtfmt.h
git add   i18n/unicode/sortkey.h
git add   i18n/unicode/tblcoll.h
git add   i18n/unicode/timezone.h
git add   i18n/unicode/translit.h
git add   i18n/unicode/tzfmt.h
git add   i18n/unicode/tznames.h
git add   i18n/unicode/ucal.h
git add   i18n/unicode/ucol.h
git add   i18n/unicode/ucurr.h
git add   i18n/unicode/udat.h
git add   i18n/unicode/udisplaycontext.h
git add   i18n/unicode/ugender.h
git add   i18n/unicode/uldnames.h
git add   i18n/unicode/ulocdata.h
git add   i18n/unicode/unum.h
git add   i18n/unicode/upluralrules.h
git add   i18n/unicode/uregex.h
git add   i18n/unicode/uspoof.h
git add   i18n/unicode/vtzone.h
git add   i18n/uspoof.cpp
git add   i18n/uspoof_conf.cpp
git add   i18n/uspoof_impl.cpp
git add   i18n/uspoof_impl.h
git add   i18n/uspoof_wsconf.cpp
git add   i18n/vtzone.cpp
git add   i18n/zonemeta.cpp
git add   i18n/zonemeta.h
git add   icudefs.mk.in
git add   io/io.vcxproj
git add   io/ufile.c
git add   io/unicode/ustdio.h
git add   layout/ContextualGlyphInsertion.h
git add   layout/ContextualGlyphSubstitution.h
git add   layout/IndicRearrangement.h
git add   layout/LETypes.h
git add   layout/LayoutEngine.cpp
git add   layout/LayoutEngine.h
git add   layout/LigatureSubstitution.h
git add   layout/LookupProcessor.cpp
git add   layout/Makefile.in
git add   layout/MorphStateTables.h
git add   layout/MorphTables.h
git add   layout/NonContextualGlyphSubst.h
git add   layout/OpenTypeLayoutEngine.cpp
git add   layout/StateTables.h
git add   layout/layout.vcxproj
git add   layout/layout.vcxproj.filters
git add   layoutex/layoutex.vcxproj
git add   runConfigureICU
git add   stubdata/icu-data-default.txt
git add   stubdata/icu_dat_generator.py
git rm stubdata/icudt50l-all.dat
git rm stubdata/icudt50l-default.dat
git add   stubdata/readme.txt
git add   stubdata/regenerate.sh
git add   stubdata/stubdata.vcxproj
git add   test/cintltst/capitst.c
git add   test/cintltst/cbiapts.c
git add   test/cintltst/ccaltst.c
git add   test/cintltst/cdateintervalformattest.c
git add   test/cintltst/cdattst.c
git add   test/cintltst/cdattst.h
git add   test/cintltst/citertst.c
git add   test/cintltst/cldrtest.c
git add   test/cintltst/cloctst.c
git add   test/cintltst/cloctst.h
git add   test/cintltst/cmsccoll.c
git add   test/cintltst/cmsgtst.c
git add   test/cintltst/cnmdptst.c
git add   test/cintltst/creststn.c
git add   test/cintltst/creststn.h
git add   test/cintltst/cucdapi.c
git add   test/cintltst/cucdapi.h
git add   test/cintltst/cucdtst.c
git add   test/cintltst/nccbtst.c
git add   test/cintltst/ncnvtst.c
git add   test/cintltst/spooftest.c
git add   test/cintltst/utf16tst.c
git add   test/cintltst/utf8tst.c
git add   test/depstest/dependencies.txt
git add   test/hdrtst/cxxfiles.txt
git add   test/intltest/Makefile.in
git add   test/intltest/calcasts.cpp
git add   test/intltest/callimts.cpp
git add   test/intltest/calregts.cpp
git add   test/intltest/caltest.cpp
git add   test/intltest/canittst.cpp
git add   test/intltest/convtest.cpp
git add   test/intltest/dcfmapts.cpp
git add   test/intltest/dcfmapts.h
git add   test/intltest/dtfmrgts.cpp
git add   test/intltest/dtfmttst.cpp
git add   test/intltest/dtfmttst.h
git add   test/intltest/dtifmtts.cpp
git add   test/intltest/dtifmtts.h
git add   test/intltest/dtptngts.cpp
git add   test/intltest/genderinfotest.cpp
git add   test/intltest/intltest.cpp
git add   test/intltest/intltest.h
git add   test/intltest/intltest.vcxproj
git add   test/intltest/intltest.vcxproj.filters
git add   test/intltest/itformat.cpp
git add   test/intltest/itspoof.cpp
git add   test/intltest/itspoof.h
git add   test/intltest/itutil.cpp
git add   test/intltest/listformattertest.cpp
git add   test/intltest/listformattertest.h
git add   test/intltest/loctest.cpp
git add   test/intltest/numfmtst.cpp
git add   test/intltest/numrgts.cpp
git add   test/intltest/rbbitst.cpp
git add   test/intltest/rbbitst.h
git add   test/intltest/sdtfmtts.cpp
git add   test/intltest/ssearch.cpp
git add   test/intltest/ssearch.h
git add   test/intltest/tfsmalls.cpp
git add   test/intltest/tsdtfmsy.cpp
git add   test/intltest/tsdtfmsy.h
git add   test/intltest/tsmthred.cpp
git add   test/intltest/tsnmfmt.cpp
git add   test/intltest/tzfmttst.cpp
git add   test/intltest/tzfmttst.h
git add   test/intltest/tzregts.cpp
git add   test/intltest/tztest.cpp
git add   test/intltest/ucdtest.cpp
git add   test/intltest/ucdtest.h
git add   test/intltest/uobjtest.cpp
git add   test/intltest/usettest.cpp
git add   test/intltest/ustrtest.cpp
git add   test/iotest/iotest.vcxproj
git add   test/letest/letest.cpp
git add   test/perf/DateFmtPerf/DateFmtPerf.vcxproj
git add   test/perf/strsrchperf/strsrchperf.cpp
git add   test/perf/strsrchperf/strsrchperf.h
git add   test/testdata/calendar.txt
git add   test/testdata/conversion.txt
git add   test/testdata/format.txt
git add   test/testdata/rbbitst.txt
git add   test/testdata/root.txt
git add   test/testdata/structLocale.txt
git add   test/testdata/test3.ucm
git add   test/testmap/Makefile.in
git add   test/testmap/testmap.c
git add   tools/ctestfw/ctestfw.vcxproj
git add   tools/genrb/derb.c
git add   tools/genrb/parse.cpp
git add   tools/makeconv/gencnvex.c
git add   tools/makeconv/genmbcs.cpp
git add   tools/pkgdata/pkgdata.cpp
git add   tools/toolutil/pkg_genc.c
git add   tools/toolutil/toolutil.vcxproj
git add   tools/toolutil/ucm.c
git add   tools/toolutil/ucm.h
