git add common/uscript_props.cpp
git add config/mh-mingw64
git add data/coll/ms_Latn.txt
git add data/coll/ms_Latn_BN.txt
git add data/coll/ms_Latn_MY.txt
git add data/coll/ms_Latn_SG.txt
git add data/curr/ar_DJ.txt
git add data/curr/ar_ER.txt
git add data/curr/ar_SO.txt
git add data/curr/bo_IN.txt
git add data/curr/de_CH.txt
git add data/curr/en_AG.txt
git add data/curr/en_BE.txt
git add data/curr/en_BS.txt
git add data/curr/en_CM.txt
git add data/curr/en_DM.txt
git add data/curr/en_FJ.txt
git add data/curr/en_GD.txt
git add data/curr/en_GH.txt
git add data/curr/en_GI.txt
git add data/curr/en_GM.txt
git add data/curr/en_GY.txt
git add data/curr/en_IN.txt
git add data/curr/en_KE.txt
git add data/curr/en_KI.txt
git add data/curr/en_KN.txt
git add data/curr/en_KY.txt
git add data/curr/en_LC.txt
git add data/curr/en_LR.txt
git add data/curr/en_LS.txt
git add data/curr/en_MG.txt
git add data/curr/en_MU.txt
git add data/curr/en_MW.txt
git add data/curr/en_NG.txt
git add data/curr/en_PG.txt
git add data/curr/en_SB.txt
git add data/curr/en_SC.txt
git add data/curr/en_SL.txt
git add data/curr/en_SS.txt
git add data/curr/en_SZ.txt
git add data/curr/en_TO.txt
git add data/curr/en_TZ.txt
git add data/curr/en_UG.txt
git add data/curr/en_VC.txt
git add data/curr/en_WS.txt
git add data/curr/en_ZM.txt
git add data/curr/es_CU.txt
git add data/curr/es_PH.txt
git add data/curr/fr_CD.txt
git add data/curr/fr_CH.txt
git add data/curr/fr_DZ.txt
git add data/curr/fr_HT.txt
git add data/curr/fr_MG.txt
git add data/curr/fr_MR.txt
git add data/curr/fr_MU.txt
git add data/curr/fr_RW.txt
git add data/curr/fr_SC.txt
git add data/curr/fr_SY.txt
git add data/curr/fr_TN.txt
git add data/curr/hr_BA.txt
git add data/curr/it_CH.txt
git add data/curr/ln_AO.txt
git add data/curr/mn.txt
git add data/curr/mn_Cyrl.txt
git add data/curr/mn_Cyrl_MN.txt
git add data/curr/mn_MN.txt
git add data/curr/ms_Latn.txt
git add data/curr/ms_Latn_BN.txt
git add data/curr/ms_Latn_MY.txt
git add data/curr/ms_Latn_SG.txt
git add data/curr/ms_MY.txt
git add data/curr/ms_SG.txt
git add data/curr/nl_SR.txt
git add data/curr/pt_CV.txt
git add data/curr/pt_MO.txt
git add data/curr/ru_BY.txt
git add data/curr/ru_KG.txt
git add data/curr/ru_KZ.txt
git add data/curr/shi_Tfng_MA.txt
git add data/curr/sq_MK.txt
git add data/curr/sw_UG.txt
git add data/lang/mn.txt
git add data/lang/mn_Cyrl.txt
git add data/lang/mn_Cyrl_MN.txt
git add data/lang/mn_MN.txt
git add data/lang/ms_BN.txt
git add data/lang/ms_Latn.txt
git add data/lang/ms_Latn_BN.txt
git add data/lang/ms_Latn_MY.txt
git add data/lang/ms_Latn_SG.txt
git add data/lang/ms_MY.txt
git add data/lang/ms_SG.txt
git add data/lang/shi_Tfng_MA.txt
git add data/locales/mn.txt
git add data/locales/mn_Cyrl.txt
git add data/locales/mn_Cyrl_MN.txt
git add data/locales/mn_MN.txt
git add data/locales/ms_Latn.txt
git add data/locales/ms_Latn_BN.txt
git add data/locales/ms_Latn_MY.txt
git add data/locales/ms_Latn_SG.txt
git add data/mappings/README.emoji
git add data/mappings/docomo-shift_jis-2012.ucm
git add data/mappings/euc-jp-2007.ucm
git add data/mappings/jisx-208.ucm
git add data/mappings/kddi-shift_jis-2012.ucm
git add data/mappings/softbank-shift_jis-2012.ucm

        	data/mappings/ucmlocal.mk
git add data/region/mn.txt
git add data/region/mn_Cyrl.txt
git add data/region/mn_Cyrl_MN.txt
git add data/region/mn_MN.txt
git add data/region/ms_BN.txt
git add data/region/ms_Latn.txt
git add data/region/ms_Latn_BN.txt
git add data/region/ms_Latn_MY.txt
git add data/region/ms_Latn_SG.txt
git add data/region/ms_MY.txt
git add data/region/ms_SG.txt
git add data/region/shi_Tfng_MA.txt
git add data/region_dalvik/
git add data/translit/az_Lower.txt
git add data/translit/az_Title.txt
git add data/translit/az_Upper.txt
git add data/translit/el_Lower.txt
git add data/translit/el_Title.txt
git add data/translit/el_Upper.txt
git add data/translit/lt_Lower.txt
git add data/translit/lt_Title.txt
git add data/translit/lt_Upper.txt
git add data/translit/nl_Title.txt
git add data/translit/tr_Lower.txt
git add data/translit/tr_Title.txt
git add data/translit/tr_Upper.txt
git add data/xml/main/mn.xml
git add data/xml/main/mn_Cyrl.xml
git add data/xml/main/ms_Latn.xml
git add data/zone/mn.txt
git add data/zone/mn_Cyrl.txt
git add data/zone/mn_Cyrl_MN.txt
git add data/zone/mn_MN.txt
git add data/zone/ms_BN.txt
git add data/zone/ms_Latn.txt
git add data/zone/ms_Latn_BN.txt
git add data/zone/ms_Latn_MY.txt
git add data/zone/ms_Latn_SG.txt
git add data/zone/ms_MY.txt
git add data/zone/ms_SG.txt
git add data/zone/shi_Tfng_MA.txt
git add i18n/compactdecimalformat.cpp
git add i18n/dangical.cpp
git add i18n/dangical.h
git add i18n/identifier_info.cpp
git add i18n/identifier_info.h
git add i18n/region.cpp
git add i18n/region_impl.h
git add i18n/scriptset.cpp
git add i18n/scriptset.h
git add i18n/unicode/compactdecimalformat.h
git add i18n/unicode/region.h
git add layout/ContextualGlyphInsertionProc2.cpp
git add layout/ContextualGlyphInsertionProc2.h
git add layout/ContextualGlyphSubstProc2.cpp
git add layout/ContextualGlyphSubstProc2.h
git add layout/GXLayoutEngine2.cpp
git add layout/GXLayoutEngine2.h
git add layout/IndicRearrangementProcessor2.cpp
git add layout/IndicRearrangementProcessor2.h
git add layout/LigatureSubstProc2.cpp
git add layout/LigatureSubstProc2.h
git add layout/MorphTables2.cpp
git add layout/NonContextualGlyphSubstProc2.cpp
git add layout/NonContextualGlyphSubstProc2.h
git add layout/SegmentArrayProcessor2.cpp
git add layout/SegmentArrayProcessor2.h
git add layout/SegmentSingleProcessor2.cpp
git add layout/SegmentSingleProcessor2.h
git add layout/SimpleArrayProcessor2.cpp
git add layout/SimpleArrayProcessor2.h
git add layout/SingleTableProcessor2.cpp
git add layout/SingleTableProcessor2.h
git add layout/StateTableProcessor2.cpp
git add layout/StateTableProcessor2.h
git add layout/SubtableProcessor2.cpp
git add layout/SubtableProcessor2.h
git add layout/TrimmedArrayProcessor2.cpp
git add layout/TrimmedArrayProcessor2.h
git add samples/udata/Makefile
git add stubdata/cnv/docomo-shift_jis-2012.cnv
git add stubdata/cnv/kddi-shift_jis-2012.cnv
git add stubdata/cnv/softbank-shift_jis-2012.cnv
git add stubdata/git_new.txt
git add stubdata/git_status.txt
git add stubdata/icudt51l-all.dat
git add stubdata/icudt51l-default.dat
git add test/intltest/colldata.cpp
git add test/intltest/colldata.h
git add test/intltest/compactdecimalformattest.cpp
git add test/intltest/regiontst.cpp
git add test/intltest/regiontst.h
git add test/testmap/readme.txt
